### ISSUE TITLE
Dynamic memory allocation for channel lock in USB driver

### ISSUE THREAD

**Issue by ddv2005** [raspberrypi/linux#102]
Hi,

Latest USB driver use dynamic allocation for channel lock inside a functions. I guess that is waste a time because it can be easily allocated only once.

https://gist.github.com/3625562

Dmitry

**Comment by popcornmix** [comment]
Does it improve iperf numbers? (or any other performance measures)

**Comment by ddv2005** [comment]
I didn't test but it should because theoretically it eliminate 500-16000 memory allocations per second.

**Comment by popcornmix** [comment]
I tested it and couldn't see an improvement in iperf. However I agree it is more efficient, so I've committed it.
Thanks.

**Comment by ghollingworth** [comment]
Dmitry,

Can you test the kernel containing the fix and close the issue when you're happy?

**Comment by ddv2005** [comment]
I tested and it is good. Thanks.

P.S. But I am still can't be happy because USB audio is still terrible and I can't find the problem without hardware USB protocol analyzer :-(.

**Comment by ghollingworth** [comment]
The problem is the same as almost all the other USB problems, in that
it isn't able to keep up properly because of poor interrupt latency in
the Linux kernel...

We're trying to get somewhere on this

Gordon

On 09/09/2012, Dmitry Dudkin notifications@github.com wrote:

> I tested and it is good. Thanks.
> 
> P.S. But I am still can't be happy because USB audio is still terrible and I
> can't find the problem without hardware USB protocol analyzer :-(.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/raspberrypi/linux/issues/102#issuecomment-8404449

## 

Sent from my mobile device

**Comment by ddv2005** [comment]
I am not sure. Now I have 3 problems with USB audio:
1. Clock drift (recording thread capture 200-3000 samples per second more that playback thread)
2. Clicking sound when USB audio device connected directly to Raspberry PI. (even with Y USB cable for external power)
3. Sometimes SSPLIT OUT transaction is failed (when device connected to external MultiTT hub) that cause reset the device.

I found that in DEBUG mode I never seen a clock drift. Deep investigation shown that if I put small delay (1-10 usec) for split transactions at end of dwc_otg_hc_start_transfer then it fix problem with clock drift even under the load. I guess that this delay prevent reordering several (playback & capture) start split transactions.
But I sill have problems #2 & #3 and no way to found the problem without hardware USB protocol analyzer. Because something wrong with split transactions and only way to found it - capture USB traffic and see what is wrong.

P.S. Do you have access to Synposys documentation for USB controller? I would be very appreciate if somebody sent me this documentation. I tried contact to Synposys but still no response.
