### ISSUE TITLE
USBFS issues with DIgilent Analog Discovery 2 devices -- FTDI

### ISSUE THREAD

**Issue by rprr** [raspberrypi/linux#2621]
I am not sure if this is the right place to post this issue. (I posted this first in the raspberrypi/firmware section. Sorry for the crosspost.) I was not sure  it was a firmware vs. linux driver issue. 

I am having issues using the following device -- Digilent Analog Discovery 2. This uses a FTDI chip and connects over USB to the Pi. 
[Analog Discovery 2](https://reference.digilentinc.com/reference/instrumentation/analog-discovery-2/start?redirect=1)
This uses a software called waveforms. 
[Waveforms Software](https://reference.digilentinc.com/reference/software/waveforms/waveforms-3/start)
There is a version for the Raspberry Pi but it does not seem to work. There is a thread on the support forum for waveforms. 
[Digilent Support Forum Thread](https://forum.digilentinc.com/topic/1713-analog-discovery-2-vs-raspberry-pi-3/)
The suggestion by the moderator/developer is that there are some low level USB/FTDI issues which leads to packet loss and cause this device to not work. Other SOC computers (e.g Banana Pro) appear to work with this device. Also, I have no problems using it on a Mac. 
The main error that shows up in /var/log/syslog is the following.
`Jul 15 22:09:27 rspi3bp kernel: [  285.039475] usb 1-1.2: usbfs: usb_submit_urb returned -121`

**Comment by JamesH65** [comment]
@p33m Something that me have been fixed in more recent firmware?

@rprr Have you tried the latest kernel?

This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.

**Comment by ramprao** [comment]
@JamesH65 -- thanks. 

Unfortunately still no luck. I have updated to the latest official kernel. 
```
$ uname -a
Linux rspi3bp 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux
```
I installed the most recent dpkg version of the packages. I'm getting an overcurrent (> 1 A) message and the device stops working. I have tried it connected to both the RPi built in USB ports as well as to a powered external hub.

In /var/log/syslog, I keep getting:
```
Jul 31 19:25:39 rspi3bp kernel: [42865.572903] ftdi_sio 1-1.2.1:1.0: device disconnected
Jul 31 19:26:13 rspi3bp kernel: [42899.225264] usb 1-1.2.1: usbfs: usb_submit_urb returned -121
Jul 31 19:27:02 rspi3bp kernel: [42948.565857] usb 1-1.2.1: usbfs: usb_submit_urb returned -121
Jul 31 19:28:12 rspi3bp kernel: [43018.891745] usb 1-1.2.1: usbfs: usb_submit_urb returned -121
Jul 31 19:28:26 rspi3bp kernel: [43031.962740] usb 1-1.2.1: usbfs: usb_submit_urb returned -121
Jul 31 19:28:26 rspi3bp kernel: [43032.771847] usb 1-1.2.1: usbfs: usb_submit_urb returned -121
Jul 31 19:29:16 rspi3bp kernel: [43082.861429] usb 1-1.2.1: usbfs: usb_submit_urb returned -121
Jul 31 19:29:23 rspi3bp kernel: [43089.051183] usb 1-1.2.1: usbfs: usb_submit_urb returned -121
Jul 31 19:29:23 rspi3bp kernel: [43089.051273] usb 1-1.2.1: usbfs: usb_submit_urb returned -121
Jul 31 19:29:28 rspi3bp kernel: [43094.571408] usb 1-1.2.1: usbfs: usb_submit_urb returned -121
```

**Comment by JamesH65** [comment]
I think the quickest fix for this is to use a Pi4, Google seems to indicate the device works on that. It seems unlikely we will be able to investigate this issue further.

**Comment by JamesH65** [comment]
Closing due to lack of activity. Please request to be reopened if you feel this issue is still relevant.
