### ISSUE TITLE
Bluetooth connection drops randomly

### ISSUE THREAD

**Issue by acolombier** [raspberrypi/linux#2832]
**Describe the bug**

I am experiencing random Bluetooth connect drop between the Pi and an audio speaker. These drops appear after a random time, sometime few minutes, sometime few hours.

Once the the drop happen, the only fix is to reboot the PI: RFKILL report no block, Bluez report an Unknown Error, hciconfig hci0 down && hciconfig hci0 up has no effect, only the dmesg seems to spot a problem.

I am using LibreElec 9 (8.95.003)

I am using both onboard Wi-Fi and Bluetooth (I upgraded to 3 to 3B+ because I read the antenna design was changed and allow both in use)

**To reproduce**

Connect a Bluetooth speaker, and start playing audio on it.

**Expected behaviour**

No drop at any time, or at least no need for reboot

**Actual behaviour**

Bluetooth getting completely unusable after drop

**System**

* Which model of Raspberry Pi? *Pi3B+*
* Which OS and version (`cat /etc/rpi-issue`)? *LibreElec 9 (8.95.003)*
* Which firmware version (`vcgencmd version`)? *bcefbb195b77d6b9a02dfbad0e1fff3b18122585 (Jan  9 2019 20:07:49)*
* Which kernel version (`uname -a`)? *4.19.14*

**Logs**

* dmesg*
```
[   xxxx] Bluetooth: hci0: hardware error 0x00
[   xxxx] Bluetooth: hci0: command 0x1003 tx timeout
[   xxxx] Bluetooth: hci0: command 0x1007 tx timeout
[   xxxx] Bluetooth: hci0: command 0x1009 tx timeout
<Keep repeating>
```

** Additional context **

I was using the RPI 3 before, with the exact same OS/Version, but this one didn't experience such a bug.

**Comment by pelwell** [comment]
We've recently received an updated Bluettooth firmware for the BCM43455 that hasn't made its way into a release yet. Can you see if it improves the symptoms for you?

1. Download the file from [here](https://drive.google.com/open?id=0B_P-i4u-SLBXZ1Njbkx6d21uaWVEYmN1MDdzMXlNY3JfUVhF).
2. Back-up the old file:
```
$ cp /lib/firmware/brcm/BCM4345C0.hcd BCM4345C0.hcd.orig
```
3. Copy in the new version:
```
$ sudo cp BCM4345C0_003.001.025.0156.0280.hcd /lib/firmware/brcm/BCM4345C0.hcd
```
4. Reboot.

To return to the original firmware, should you need to:
```
$ sudo cp BCM4345C0.hcd.orig /lib/firmware/brcm/BCM4345C0.hcd
```

**Comment by MilhouseVH** [comment]
@pelwell as this is LibreELEC the firmware should be copied to
```
/storage/.config/firmware/brcm/BCM4345C0.hcd
```
and there is no need to backup the existing firmware (which is in the read-only squashfs).

I've actually been including the new Bluetooth firmware in LibreELEC test builds for the last 10 days ([not yet merged](https://github.com/LibreELEC/brcmfmac_sdio-firmware-rpi/pull/10)) since build [`#0117`](https://forum.kodi.tv/showthread.php?tid=298461&pid=2810083#pid2810083) so upgrading from 8.95.003 to a recent nightly will automatically include the new firmware (along with 4.19.17 in the latest [`#0126`](https://forum.kodi.tv/showthread.php?tid=298461&pid=2813074#pid2813074) release).

However upgrading _only_ the Bluetooth firmware will result in a simplified before/after testing scenario, which might be the best option for now.

**Comment by pelwell** [comment]
Thanks, @MilhouseVH.

**Comment by acolombier** [comment]
Thanks @pelwell and @MilhouseVH. I have just installed the driver at the indicated location, I will come back here for the result of this fix.

**Comment by acolombier** [comment]
Unfortunately, I'm still experiencing the same issue. I don't have a computer with me currently, so I can't check if `dmesg` is logging the same error, but the symptoms are strictly the same. Do I have a way to ensure the new driver is loaded correctly?

**Comment by pelwell** [comment]
I haven't found a way of reading the version of the loaded firmware, but you can extract version info from the firmware file using strings:
```
pi@raspberrypi:~$ strings /lib/firmware/brcm/BCM4345C0.hcd | grep Raspberry
&BCM43455 37.4MHz Raspberry Pi 3+-0156
```

**Comment by orclex** [comment]
Same problem with bluetooth connection drops here. Only a pi restart helps, bluetooth restart does nothing.

Raspberry Pi 3B+
Raspbian GNU/Linux 10 (buster)
$ _strings /lib/firmware/brcm/BCM4345C0.hcd | grep Raspberry_
&BCM43455 37.4MHz Raspberry Pi 3+-0159

**Comment by iczero** [comment]
Same problem here. After what seems to be a random period of time, an error occurs and bluetooth stops working. Restarting hciuart reports the device is not responding.

```
$ strings /lib/firmware/brcm/BCM4345C0.hcd | grep Raspberry
&BCM43455 37.4MHz Raspberry Pi 3+-0156
```

**Comment by pelwell** [comment]
Which kernel versions are you all running (`uname -a`)? The recent 4.19.58 release includes a trial fix for a UART driver bug that would cause it to lose chunks of characters under the right conditions. You can try the new kernel by running `sudo rpi-update` (I'm not aware of any major issues with the current testing builds, but it's wise to make a backup first and not run bleeding-edge firmware on systems you can't afford to be without).

**Comment by JamesH65** [comment]
@acolombier @iczero @orclex Did moving to 4.19.58 fix your issues?

**Comment by notare-alname** [comment]
I had similar issues and rpi-update solved it for me.

**Comment by orclex** [comment]
> @acolombier @iczero @orclex Did moving to 4.19.58 fix your issues?
Unfortunately I cannot test it anymore. I've disabled the bluetooth device and added an external bluetooth USB device which is working without problems. Now the RPi is working productive and I cannot experiment anymore. Maybe someone other can confirm that it is working now?

**Comment by rixwoodling** [comment]
This issue still appears to be open as OP has described on version 4.19.66, RPi3B+.
Bluetooth connects, audio plays. Then, audio drops at a random time and I am unable to determine why it drops and how to reconnect without rebooting as a workaround. It is worth noting that when attempting to 'power on' bluetooth after a dropout, it never does:

`sudo bluetoothctl`
```
Agent registered
[bluetooth]# show
: 
Powered: no
: 
[bluetooth]# power on
[bluetooth]# show
: 
Powered: no
: 
Failed to set power on: org.bluez.Error.Failed
```
---
```
Linux 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv71 GNU/Linux
&BCM43455 37.4MHz Raspberry Pi 3+-0156 # Raspbian 10 ( Buster )
```

**Comment by schornstephan** [comment]
I experience the same problem as OP.
I investigated a little and found out, that the Bluetooth device, the BCM4345, seems to rest in an unusable state. As a hardware defect seems highly unlikely, I'd guess there is a problem with the firmware as already stated. However, Rasbian for example doesn't seem to be affected although it uses the same firmware (can someone confirm that?).
Are there any things that Libreelec does differently than Raspbian for example when sending signals to the chip? It should be something that happens during normal operation, like keep alive signals or something like that.

However, as I'm no expert on that, I tried a different approach to achieve a workaround:
Power cycling the BCM4345 during normal operation. It seems to be possible for USB devices by echoing signals to /sys/bus/usb/devices[...]/control.
But I was not successful in determining how this chip is connected to the board. It doesn't seem to be usb, my best guess is sdio. I also wasn't successful in turning off any sdio device. I just got an sh: write error: Invalid argument when attempting to write into the control file.

Has anybody any ideas about this powercycling effort? If it's possible to do it, it was easy to implement it into some script...
I am at the limit of my knowledge here...

**Comment by orclex** [comment]
Since Raspbian 10 runs on my Pi 3B+, I can unfortunately say that it is definitely affected, too.

**Comment by schornstephan** [comment]
Thanks!
That's too bad.
I've got a Rasbian running, too. I've used Bluetooth audio every now and then on it and never experienced these drops on it. Probably, that was just a coincidence. Randomly occurring errors really are a pain in the a...

**Comment by ole1986** [comment]
So sad, same here:

```
strings /lib/firmware/brcm/BCM4345C0.hcd | grep Raspberry
&BCM43455 37.4MHz Raspberry Pi 3+-0159
```

Sporadically breaks and only a reboot is the solution

**Comment by schornstephan** [comment]
> @acolombier @iczero @orclex Did moving to 4.19.58 fix your issues?

I'm on 4.19.66 and nothing has changed. The "waiting for input" label can be removed.

**Comment by hajo62** [comment]
I see the same.
If no solution could be found, maybe someone has an idea how to re-enable without need to boot the whole system?
 
```
$uname
4.19.66-v7+

$strings /lib/firmware/brcm/BCM4345C0.hcd | grep Raspberry
&BCM43455 37.4MHz Raspberry Pi 3+-0156

$dmesg | grep Bluetooth
[   12.467080] Bluetooth: Core ver 2.22
[   12.467239] Bluetooth: HCI device and connection manager initialized
[   12.467262] Bluetooth: HCI socket layer initialized
[   12.467277] Bluetooth: L2CAP socket layer initialized
[   12.467324] Bluetooth: SCO socket layer initialized
[   12.525705] Bluetooth: HCI UART driver ver 2.3
[   12.525719] Bluetooth: HCI UART protocol H4 registered
[   12.525805] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   12.526016] Bluetooth: HCI UART protocol Broadcom registered
[   12.917144] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   12.917152] Bluetooth: BNEP filters: protocol multicast
[   12.917166] Bluetooth: BNEP socket layer initialized
[   17.484314] Bluetooth: RFCOMM TTY layer initialized
[   17.484343] Bluetooth: RFCOMM socket layer initialized
[   17.484382] Bluetooth: RFCOMM ver 1.11

$sudo bluetoothctl
[NEW] Controller BB:22:EE:88:66:77 raspberrypi [default]
[NEW] Device 44:66:AA:DD:FF:DD MJ_HT_V1
[bluetooth]# show
Controller B8:27:EB:82:66:70
	Name: raspberrypi
	Alias: raspberrypi
	Class: 0x480000
	Powered: yes
	Discoverable: no
	Pairable: yes
	UUID: Headset AG                (00001112-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	UUID: Audio Source              (0000110a-0000-1000-8000-00805f9b34fb)
	UUID: Handsfree Audio Gateway   (0000111f-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v1D6Bp0246d052B
	Discovering: no


```

**Comment by pelwell** [comment]
I have a script I call btreset that I've published on other threads:
```
sudo killall hciattach
if grep -a Zero /proc/device-tree/model; then
  raspi-gpio set 45 op dl
  sleep 1
  raspi-gpio set 45 op dh
else
  /opt/vc/bin/vcmailbox 0x38041 8 8 128 0
  sleep 1
  /opt/vc/bin/vcmailbox 0x38041 8 8 128 1
fi
sleep 4
sudo btuart
```

**Comment by hajo62** [comment]
Thanks for the script @pelwell : Unfortunately it does not solve my problem and the last command results in a timeout.

sudo btuart:
```
bcm43xx_init
Initialization timed out.
```

**Comment by pelwell** [comment]
You could try increasing the `sleep 1`s to `sleep 2`s (or make them all 10 to be certain), but that really ought to hard-reset the BT modem. If it still doesn't work with the extra delays, what does `raspi-gpio get 30-33` report?

**Comment by hajo62** [comment]
Made all three sleeps to 10s. Still `Initialization timed out.`
```
$raspi-gpio get 30-33
GPIO 30: level=0 fsel=7 alt=3 func=CTS0
GPIO 31: level=1 fsel=7 alt=3 func=RTS0
GPIO 32: level=1 fsel=7 alt=3 func=TXD0
GPIO 33: level=1 fsel=7 alt=3 func=RXD0
```

**Comment by pelwell** [comment]
Does the reset work before the connection drops?

**Comment by hajo62** [comment]
I will try, but than the connection is on again and I can't say how long it takes, till it drops again. Last time it took 24h. Sometimes it is several days..

**Comment by pelwell** [comment]
If it's not too late, can you capture the output of `dmesg` before rebooting?

**Comment by pelwell** [comment]
Unless you are frequently disconnecting and reconnecting USB devices, or there is some problem in the system, the kernel log ought to be quiet. I'm curious to see if there was any clue as to why the BT modem died.

**Comment by hajo62** [comment]
Has been to late but term history had the output before running your script.
Putted the dmseg output to dropbox and will remove in an hour.
https://www.dropbox.com/s/3r5dh665opy7seh/dmesg.out?dl=0  (removed sharing...)

I have just one device connected to my Pi...

How would I mail a log only to you without storing in github?

**Comment by pelwell** [comment]
I saw the log before it disappeared. There was nothing BT-related, just a lot of Docker messages.

Let me know when you've managed to try a reset before the failure.

**Comment by hajo62** [comment]
Here the output of your script:
```
0x00000020 0x80000000 0x00038041 0x00000008 0x00000008 0x00000000 0x00000000 0x00000000 
0x00000020 0x80000000 0x00038041 0x00000008 0x00000008 0x00000000 0x00000001 0x00000000 
bcm43xx_init
Initialization timed out.
```

Looks like I do not receive values from that sensor after I ran the script.
```
$ dmesg | grep Bluetooth
[   11.651060] Bluetooth: Core ver 2.22
[   11.651120] Bluetooth: HCI device and connection manager initialized
[   11.651136] Bluetooth: HCI socket layer initialized
[   11.651143] Bluetooth: L2CAP socket layer initialized
[   11.651164] Bluetooth: SCO socket layer initialized
[   11.695777] Bluetooth: HCI UART driver ver 2.3
[   11.695788] Bluetooth: HCI UART protocol H4 registered
[   11.695840] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   11.695992] Bluetooth: HCI UART protocol Broadcom registered
[   12.252713] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   12.252727] Bluetooth: BNEP filters: protocol multicast
[   12.252756] Bluetooth: BNEP socket layer initialized
[   12.462355] Bluetooth: RFCOMM TTY layer initialized
[   12.462380] Bluetooth: RFCOMM socket layer initialized
[   12.462403] Bluetooth: RFCOMM ver 1.11
[43032.385004] Bluetooth: hci0: sending frame failed (-49)
```

**Comment by hajo62** [comment]
@pelwell : And tried again directly after reboot and after getting the first value from the sensor and got the same message as shown above...

**Comment by rbauduin** [comment]
I am experiencing the same problem with a raspberry pi zero W. @pelwell 's script had some effect: the pi reconnected and disconnected 3 times , but then stayed disconnected. (so it had some effect, but didn't get the system working again).
Some additional info:
```
pi@wc:~ $ cat /etc/rpi-issue
Raspberry Pi reference 2019-09-26
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 80d486687ea77d31fc3fc13cf3a2f8b464e129be, stage2
pi@wc:~ $ vcgencmd version
Sep 24 2019 17:37:19 
Copyright (c) 2012 Broadcom
version 6820edeee4ef3891b95fc01cf02a7abd7ca52f17 (clean) (release) (start)
pi@wc:~ $ uname -a
Linux wc 4.19.75+ #1270 Tue Sep 24 18:38:54 BST 2019 armv6l GNU/Linux
```

**Comment by rbauduin** [comment]
As only a reboot gets bluetooth working again, I thought I'd share how I automated things.
I added this to a shell script started as a service on the my pi (it could also be added as a new service, similarly to what is done below for the btreboot service):
```
# USB_ADDR is the address of the usb peer of the form XX:XX:XX:XX:XX:XX
(while true; do hcitool lq $USB_ADDR &> /dev/null; sleep 1; done)&
```
This will trigger an error message in dmesg output, which I then monitor from a btreboot service.
Systemd service:
```
[Unit]
Description=Reboot is we detect a bt error in dmesg

[Service]
Type=simple
ExecStart=/usr/local/bin/btreboot.sh

[Install]
WantedBy=multi-user.target
```
And the script called by the service:
```
#!/bin/bash
# reboot if bluetooth problem is detected in dmesg
dmesg -w | egrep "Bluetooth: hci0: command .* tx timeout" --line-buffered | while read l; do reboot; done
```

Hope this helps

**Comment by ole1986** [comment]
Not to blame your script, but this can simply not the solution of restating the raspberry.

 But thanks for the idea

**Comment by rbauduin** [comment]
> Not to blame your script, but this can simply not the solution of restating the raspberry.

I agree with you it isn't meant to be the solution. But in the meantime, I needed a work-around  and thought I'd share it. Looking forward to deploying a proper fix though!

**Comment by gmazilla** [comment]
Have the same problem as TS.
Bluetooth stops working after about 30 minutes of audio streaming to BT headset BQ-618.
dmseg says:

```
...
[   28.339907] Bluetooth: RFCOMM ver 1.11
[   28.349654] fuse init (API version 7.27)
[  111.670567] Bluetooth: HIDP (Human Interface Emulation) ver 1.2
[  111.670600] Bluetooth: HIDP socket layer initialized
[  111.677811] hid-generic 0005:099A:0500.0003: unknown main item tag 0x0
[  111.678192] input: Bluetooth Mouse as /devices/platform/soc/3f201000.serial/tty/ttyAMA0/hci0/hci0:11/0005:099A:0500.0003/input/input4
[  111.678819] hid-generic 0005:099A:0500.0003: input,hidraw2: BLUETOOTH HID v1.1b Mouse [Bluetooth Mouse] on b8:27:eb:d9:46:15
[  300.389385] input: 37:3E:29:48:30:C5 as /devices/virtual/input/input5
[11614.292098] input: 37:3E:29:48:30:C5 as /devices/virtual/input/input6
[11622.631218] hid-generic 0005:05D6:000A.0004: unknown main item tag 0x0
[11622.631719] input: BQ-618 Consumer Control as /devices/platform/soc/3f201000.serial/tty/ttyAMA0/hci0/hci0:12/0005:05D6:000A.0004/input/input7
[11622.640898] hid-generic 0005:05D6:000A.0004: input,hidraw3: BLUETOOTH HID v2.40 Device [BQ-618] on b8:27:eb:d9:46:15
[11720.759024] input: 37:3E:29:48:30:C5 as /devices/virtual/input/input8
[12901.325100] Bluetooth: hci0: hardware error 0x00
[12905.900717] Bluetooth: hci0: command 0x1003 tx timeout
[12907.981199] Bluetooth: hci0: command 0x1001 tx timeout
[12910.061025] Bluetooth: hci0: command 0x1009 tx timeout
[13129.581699] Bluetooth: hci0: command 0x1003 tx timeout
[13131.661726] Bluetooth: hci0: command 0x1001 tx timeout
[13133.741732] Bluetooth: hci0: command 0x1009 tx timeout
[13401.345094] Bluetooth: hci0: command 0x1003 tx timeout
[13403.425298] Bluetooth: hci0: command 0x1001 tx timeout
[13405.505210] Bluetooth: hci0: command 0x1009 tx timeout
```
'bluetoothctl show' says BT is not powered.
'bluetoothctl power on' fails.

I have RPI3B+
Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

**Comment by samueleforconi** [comment]
Hi,
same problem here with a RPi 3B+, running Raspbian Lite (Stretch).

`$ cat /proc/device-tree/model`
`Raspberry Pi 3 Model B Plus Rev 1.3`

`$ strings /lib/firmware/brcm/BCM4345C0.hcd | grep Raspberry`
`&BCM43455 37.4MHz Raspberry Pi 3+-0156`

`$ raspi-gpio get 30-33`
`GPIO 30: level=0 fsel=7 alt=3 func=CTS0`
`GPIO 31: level=1 fsel=7 alt=3 func=RTS0`
`GPIO 32: level=1 fsel=7 alt=3 func=TXD0`
`GPIO 33: level=1 fsel=7 alt=3 func=RXD0`

`$ uname -a`
`Linux raspberry-pi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux`

To debug the problem, I have disabled both `hciuart.service` and `bluetooth.service` from starting up at boot. 

Then I login on the system and run:
`$ sudo /usr/bin/hciattach -n /dev/serial1 bcm43xx 3000000 flow - b8:27:eb:78:11:21`
`bcm43xx_init`
`Flash firmware /lib/firmware/brcm/BCM4345C0.hcd`
`Set BDADDR UART: b8:27:eb:78:11:21`
`Set Controller UART speed to 3000000 bit/s`
`Device setup complete`

Then, I stop `hciattach` pressing `CTRL+C` and run:
`sudo /opt/vc/bin/vcmailbox 0x38041 8 8 128 0`
...wait for a few seconds, and run:
`sudo /opt/vc/bin/vcmailbox 0x38041 8 8 128 1`
(these commands should perform an hw-reset of the bluetooth peripheral)

But then, if I try to restart the bluetooth interface:
`$ sudo /usr/bin/hciattach -n /dev/serial1 bcm43xx 3000000 flow - b8:27:eb:78:11:21`
`bcm43xx_init`
`Initialization timed out.`

And the only way to recover the bluetooth interface is to reboot the Raspberry.

**Comment by pelwell** [comment]
A bug was found in the UART driver last week and fixed/worked around. The fix is in the kernel available by running "sudo rpi-update". Update to the new kernel and see Bluetooth is more stable.

N.B. The "fix" will have no effect on the ability to reset the modem should something go wrong (that still needs to be investigate), but it might avoid the need for the reset in the first place.

**Comment by samueleforconi** [comment]
Hi Phil, 
regarding bluetooth/uart stability, I have found problems only on RPi 3B v1.2 that doesn't have the flow control. In that device I set the uart baudrate to 460800 to minimize the probability of errors on uart (with the default baudrate set at 921600 I have experienced many hci errors).
However, as we are using the RPi as a headless bluetooth receiver (that is expected to run for days/months/years...), a reset functionality will be strongly desired.
Thanks for your help, I'll stay tuned for updates on this issue.

**Comment by hajo62** [comment]
> A bug was found in the UART driver last week and fixed/worked around. The fix is in the kernel available by running "sudo rpi-update". Update to the new kernel and see Bluetooth is more stable.
> 
> N.B. The "fix" will have no effect on the ability to reset the modem should something go wrong (that still needs to be investigate), but it might avoid the need for the reset in the first place.

I made the upgrade some days ago and unfortunately I had a connection
drop after **1 day 22 hours**.  Second connection
drop after **6 days 20h**.

And now alive since **9 days 9 h**.

Thanks for the patch. Much better than before!

**Comment by pelwell** [comment]
I've been following this up with Cypress, and they are confident that the reset pin should be working. Trying again I found that the second invocation of btreset worked, and this pattern seemed to be repeatable. The difference with the second run is that there is no hciattach process, which made me wonder if the asynchronous nature of killing hciattach was causing problems.

Try this modified version of the script:
```
sudo killall hciattach
sleep 2
if grep -a Zero /proc/device-tree/model; then
  raspi-gpio set 45 op dl
  sleep 1
  raspi-gpio set 45 op dh
else
  /opt/vc/bin/vcmailbox 0x38041 8 8 128 0
  sleep 1
  /opt/vc/bin/vcmailbox 0x38041 8 8 128 1
fi
sleep 4
sudo btuart
```
Note the addition of the `sleep 2` after the `sudo killall hciattach`. This extra delay has (in my testing) made the reset reliable.

**Comment by samueleforconi** [comment]
Hi Phil,
I tried your script on a RPi3B+, but with no luck... can you tell me if I'm doing something wrong.

This is the hardware used for testing:
`pi@raspberrypi:/ $ cat /proc/cpuinfo`
`...`
`Hardware        : BCM2835`
`Revision        : a020d3`
`...`

`pi@raspberrypi:/ $ uname -a`
`Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux`

`pi@raspberrypi:~ $ cat /etc/os-release`
`PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"`
`NAME="Raspbian GNU/Linux"`
`VERSION_ID="9"`
`VERSION="9 (stretch)"`
`VERSION_CODENAME=stretch`
`ID=raspbian`
`ID_LIKE=debian`
`HOME_URL="http://www.raspbian.org/"`
`SUPPORT_URL="http://www.raspbian.org/RaspbianForums"`
`BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs`

Then this is the list of commands that I have run to test your script:

1. Check running processes (that refers to the Bluetooth hardware):
`pi@raspberrypi:~ $ ps aux`
`USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND`
`...`
`root       445  0.0  0.0   1912   108 ?        S    10:56   0:00 /usr/bin/hciattach /dev/serial1 bcm43xx 3000000 flow - b8:27:eb:de:2c:bd`
`root       452  0.0  0.3   7596  3628 ?        Ss   10:56   0:00 /usr/libexec/bluetooth/bluetoothd -E`
`pi        1406  0.8  0.4   6268  4404 pts/0    Ss   10:57   0:00 -bash`
`pi        1526  0.0  0.3   7740  2860 pts/0    R+   10:57   0:00 ps aux`

2. Create the bluetoooth test reset script:
`pi@raspberrypi:~ $ cd /tmp/`
`pi@raspberrypi:/tmp $ sudo nano test-reset.sh`
`pi@raspberrypi:/tmp $ cat test-reset.sh`
`#!/bin/bash`
`sudo killall hciattach`
`sleep 2`
`if grep -a Zero /proc/device-tree/model; then`
`  raspi-gpio set 45 op dl`
`  sleep 1`
`  raspi-gpio set 45 op dh`
`else`
`  /opt/vc/bin/vcmailbox 0x38041 8 8 128 0`
`  sleep 1`
`  /opt/vc/bin/vcmailbox 0x38041 8 8 128 1`
`fi`
`sleep 4`
`sudo btuart`
`pi@raspberrypi:/tmp $ sudo chmod 755 test-reset.sh`

3. Run the script:
`pi@raspberrypi:/tmp $ ./test-reset.sh`
`0x00000020 0x80000000 0x00038041 0x00000008 0x00000008 0x00000000 0x00000000 0x00000000`
`0x00000020 0x80000000 0x00038041 0x00000008 0x00000008 0x00000000 0x00000001 0x00000000`
`bcm43xx_init`
`Failed to reset chip, command failure`
`Can't initialize device: Success`
`pi@raspberrypi:/tmp $`

I'm doing something wrong?
How are you checking the bluetooth reset functionality?

**Comment by pelwell** [comment]
I tested the script on a 4B, not a 3B+, but it should be the same circuitry around the 43455. Trying now I also see a failure to reset.

1. I have had success with the following version, but it has the considerable disadvantage that it takes out the WiFi connection as well - it would just be good to get some confirmation that you see the same behaviour:
```
sudo killall hciattach
sleep 2
if grep -a Zero /proc/device-tree/model; then
  raspi-gpio set 45 op dl
  sleep 1
  raspi-gpio set 45 op dh
else
  /opt/vc/bin/vcmailbox 0x38041 8 8 128 0
  /opt/vc/bin/vcmailbox 0x38041 8 8 129 0
  sleep 1
  /opt/vc/bin/vcmailbox 0x38041 8 8 129 1
  sleep 1
  /opt/vc/bin/vcmailbox 0x38041 8 8 128 1
fi
sleep 4
sudo btuart
```

2. What is your use case on the 3B+ that requires a hard reset? It would be good to reproduce it here so I can forward it to Cypress.

3. Can you try an HCI reset command instead?
```
$ sudo hciconfig reset
```

**Comment by pelwell** [comment]
> How are you checking the bluetooth reset functionality?

`while true; do hcitool clock; sleep 2; done` is a useful way to monitor the BT status. Not only does it show when the connection is lost, the Clock value (which is normally constantly incrementing) gets reset to zero when the device is reset.

**Comment by samueleforconi** [comment]
Hi Phil,
I'll try to describe here as best as I can the tests that I have done.

I'm actually using the RPi as a headless BLE receiver.
In the previous test, the OS was booted and my BLE receiver daemon was started (by systemd), then I killed it and tested your reset script (and I get the previously reported results).

Now, I have disabled the startup of my BLE receiver daemon, so the only Bluetooth-related processes that are running are `hciattach` and `bluetoothd`, and repeated the test.

**Please note: each test has been done rebooting the RPi.**

**Test 1 - Only Bluetooth pin toggled.**
Script used:
```
sudo killall hciattach
sleep 2
if grep -a Zero /proc/device-tree/model; then
  raspi-gpio set 45 op dl
  sleep 1
  raspi-gpio set 45 op dh
else
  /opt/vc/bin/vcmailbox 0x38041 8 8 128 0
  sleep 1
  /opt/vc/bin/vcmailbox 0x38041 8 8 128 1
fi
sleep 4
sudo btuart
```
Result of running test-reset script:
```
pi@raspberrypi:/tmp $ ./test-reset.sh
0x00000020 0x80000000 0x00038041 0x00000008 0x00000008 0x00000000 0x00000000 0x00000000
0x00000020 0x80000000 0x00038041 0x00000008 0x00000008 0x00000000 0x00000001 0x00000000
bcm43xx_init
Initialization timed out.
```

**Test 2 - Both Wifi and Bluetooth pins toggled.**
Script used:
```
sudo killall hciattach
sleep 2
if grep -a Zero /proc/device-tree/model; then
  raspi-gpio set 45 op dl
  sleep 1
  raspi-gpio set 45 op dh
else
  /opt/vc/bin/vcmailbox 0x38041 8 8 128 0
  /opt/vc/bin/vcmailbox 0x38041 8 8 129 0
  sleep 1
  /opt/vc/bin/vcmailbox 0x38041 8 8 129 1
  sleep 1
  /opt/vc/bin/vcmailbox 0x38041 8 8 128 1
fi
sleep 4
sudo btuart
```
Result of running test-reset script:
```
pi@raspberrypi:/tmp $ ./test-reset.sh
0x00000020 0x80000000 0x00038041 0x00000008 0x00000008 0x00000000 0x00000000 0x00000000
0x00000020 0x80000000 0x00038041 0x00000008 0x00000008 0x00000000 0x00000000 0x00000000
0x00000020 0x80000000 0x00038041 0x00000008 0x00000008 0x00000000 0x00000001 0x00000000
0x00000020 0x80000000 0x00038041 0x00000008 0x00000008 0x00000000 0x00000001 0x00000000
bcm43xx_init
Cannot open directory '/etc/firmware': No such file or directory
Patch not found, continue anyway
Set BDADDR UART: b8:27:eb:de:2c:bd
Set Controller UART speed to 3000000 bit/s
Device setup complete
```

**Test 3 - Only Wifi pin toggled.**
Script used:
```
sudo killall hciattach
sleep 2
if grep -a Zero /proc/device-tree/model; then
  raspi-gpio set 45 op dl
  sleep 1
  raspi-gpio set 45 op dh
else
  /opt/vc/bin/vcmailbox 0x38041 8 8 129 0
  sleep 1
  /opt/vc/bin/vcmailbox 0x38041 8 8 129 1
fi
sleep 4
sudo btuart
```
Result of running test-reset script:
```
pi@raspberrypi:/tmp $ ./test-reset.sh
0x00000020 0x80000000 0x00038041 0x00000008 0x00000008 0x00000000 0x00000000 0x00000000
0x00000020 0x80000000 0x00038041 0x00000008 0x00000008 0x00000000 0x00000001 0x00000000
bcm43xx_init
Cannot open directory '/etc/firmware': No such file or directory
Patch not found, continue anyway
Set BDADDR UART: b8:27:eb:de:2c:bd
Set Controller UART speed to 3000000 bit/s
Device setup complete
```


**Test 4 - Re-enable BLE receiver daemo and toggle Wifi pin only.**
`sudo systemctl enable ble-recvd.service`
`sudo reboot`

Script used:
```
sudo killall hciattach
sleep 2
if grep -a Zero /proc/device-tree/model; then
  raspi-gpio set 45 op dl
  sleep 1
  raspi-gpio set 45 op dh
else
  /opt/vc/bin/vcmailbox 0x38041 8 8 129 0
  sleep 1
  /opt/vc/bin/vcmailbox 0x38041 8 8 129 1
fi
sleep 4
sudo btuart
```
Result of running test-reset script:
```
pi@raspberrypi:/tmp $ ./test-reset.sh
0x00000020 0x80000000 0x00038041 0x00000008 0x00000008 0x00000000 0x00000000 0x00000000
0x00000020 0x80000000 0x00038041 0x00000008 0x00000008 0x00000000 0x00000001 0x00000000
bcm43xx_init
Cannot open directory '/etc/firmware': No such file or directory
Patch not found, continue anyway
Set BDADDR UART: b8:27:eb:de:2c:bd
Set Controller UART speed to 3000000 bit/s
Device setup complete
```

It seems that toggling pin 129 works to perform the reset of the BLE module, while pin 128 does nothing (in my setup). I don't know the schematic of how these pins are connected, but are we sure that the reset pin of the BLE module is on 128? 
Let me know if I can perform some other tests to help understanding what's going on...

**Comment by pelwell** [comment]
I now have two different 3B+s, one of which resets as expected and one of which behaves exactly like yours.

Which build revision do you have (`cat /proc/device-tree/model`)?

**Comment by samueleforconi** [comment]
```
$ cat /proc/device-tree/model
Raspberry Pi 3 Model B Plus Rev 1.3
```

```
$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : a020d3
Serial          : 0000000032748617
```

**Comment by pelwell** [comment]
After a bit of archaeology I can confirm that you have what could be called a rev 1.4 3B+, even though the OTP still marks it as a 1.3. The design had to be changed to accommodate a slightly changed 43455 part, and that forced the removal of the independent BT_ON signal (GPIO 0 on the expander, a.k.a. GPIO 128); it is wired to WL_ON (GPIO 1/129) instead.

Unfortunately this means that if you are using WiFi then you can't issue a hard reset to Bluetooth.

Can you try the "sudo hciconfig reset" command as an alternative to toggling BT_ON?

**Comment by samueleforconi** [comment]
Ok, I have understand.
Regarding the software reset (hci command), it should work if the hci interface is up and running correctly. The problem is that on some RPis we get the hci interface completely stuck and checking `dmesg` we have these logs:
```
[205797.968484] Bluetooth: hci0: advertising data len corrected
[294998.085946] Bluetooth: hci0: advertising data len corrected
[704512.084701] Bluetooth: hci0: advertising data len corrected
[988104.776316] Bluetooth: hci0: advertising data len corrected
[1579091.893507] Bluetooth: hci0: advertising data len corrected
[2202761.890594] Bluetooth: hci0: advertising data len corrected
...
[2403905.221839] Bluetooth: hci0: Frame reassembly failed (-84)
[2403905.221941] Bluetooth: hci0: Frame reassembly failed (-84)
[2403905.222116] Bluetooth: hci0: Frame reassembly failed (-84)
[2403905.222290] Bluetooth: hci0: Frame reassembly failed (-84)
[2403905.222458] Bluetooth: hci0: Frame reassembly failed (-84)
[2403905.222655] Bluetooth: hci0: Frame reassembly failed (-84)
[2916857.093301] Bluetooth: hci0: advertising data len corrected
```
I don't know if these errors could cause the hci interface to stop working, but for this reason, I was looking for a hardware reset of the bluetooth module, because on these devices the hci interface is not working / not responsive anymore.

**Comment by henzef** [comment]
on my end the hciconfig reset does not fix the issue (even though it does not raise an error), but the reset via WL_ON pin works fine.

**Comment by pelwell** [comment]
I haven't seen errors like that on a Pi with BT flow control (Zero W, 3B+, 3A+, 4B) running the latest kernel (current Raspbian raspberrypi-kernel package, or rpi-update). If you have a reliable way to provoke them then I'll get Cypress on it.

**Comment by samueleforconi** [comment]
We are still trying to understand if there's a particular device or a situation that could trigger these errors (we develop bluetooth devices and sometimes in our office / laboratories we have thousands of BLE device advertising toghether so it's not simple to detect when and why those errors occurs...).
Anyway, thanks for the previous investigation regarding the BT_RESET pin problem!

**Comment by henzef** [comment]
I am also trying to find the exact steps to reproduce the issue we are having. I don't know when I will have time for that though.

**Comment by pelwell** [comment]
Don't waste your time testing anything older than Linux 4.19.100 on rpi-4.19.y (upstream kernels won't include the fix). 5.x kernels will have different version thresholds.

**Comment by henzef** [comment]
which fix are you refering to? I can't find a related change in https://github.com/Hexxeh/rpi-firmware/commit/0dfefdceed89582e9ddda856a9056739d0cf9059

**Comment by pelwell** [comment]
The fix is:
```
kernel: tty: amba-pl011: Avoid rare write-when-full error
See: raspberrypi/firmware#1150
```
in https://github.com/Hexxeh/rpi-firmware/commit/15261920fa8cb85efed3920c715d10e5b1e848dd, i.e. the one before 4.19.102.

**Comment by mminelli** [comment]
Same thing happens to me on osmc with RPi3.
Here is some information about my system:
 
```
$ uname -a
Linux osmc 4.19.55-6-osmc #1 SMP PREEMPT Sun Nov 3 22:15:28 UTC 2019 armv7l GNU/Linux

$ cat /proc/device-tree/model
Raspberry Pi 3 Model B Plus Rev 1.3

$ strings /lib/firmware/brcm/BCM4345C0.hcd | grep Raspberry
&BCM43455 37.4MHz Raspberry Pi 3+-0141
```

Any idea would be much appreciated.

**Comment by pelwell** [comment]
I think there is a BT/WiFi coexistence problem with the new firmware. You can track the issue here: https://github.com/RPi-Distro/firmware-nonfree/issues/8

**Comment by mminelli** [comment]
Thanks for the reply @pelwell. In my case, the wifi adapter is off, but it should be said that I'm using OSMC distribution (for Kodi), and it's not on the latest version of the packages, including bluez. Perhaps Arch for ARM would help because it has more recent packages. I will give it a try in the coming days and report back.

**Comment by mminelli** [comment]
I can confirm that it's working fine with Arch ARM on a Raspberry Pi 3 and Kodi + Pulseaudio.

**Comment by agungpambudi55** [comment]
After reading the issue here, I tried to conclude, and it worked for me. I have tested many times the results are satisfactory compared to restarting a PC or mini-PC. The problem is solved by creating a program file to check the bluetooth status so when the status is DOWN INIT RUNNING it will automatically reset the bluetooth firmware.

https://github.com/agungpambudi55/bluetooth-down-init-running

**Comment by mgrey** [comment]
Any updates here? 
Same issue with Pi4 with 5.10.17-v7l+ #1403 with latest bluez-firmware (1.2-4+rpt8)
hcitool dev empty, frequent after reboot at least.
Mar 10 10:39:37 mypi kernel: [  303.197340] Bluetooth: hci0: hardware error 0x00
Mar 10 10:39:39 mypi kernel: [  305.277321] Bluetooth: hci0: command 0x1003 tx timeout
Mar 10 10:39:41 mypi kernel: [  307.357358] Bluetooth: hci0: command 0x1001 tx timeout
Mar 10 10:39:43 mypi kernel: [  309.437386] Bluetooth: hci0: command 0x1009 tx timeout
Mar 10 10:39:47 mypi kernel: [  313.437509] Bluetooth: hci0: hardware error 0x00
@agungpambudi55 script works to reset
I'm just using bluetooth as a passive listener

**Comment by bjo81** [comment]
> I can confirm that it's working fine with Arch ARM on a Raspberry Pi 3 and Kodi + Pulseaudio.

Nice to hear, do you use armv7h or aarch64? I'm getting the issues with 5.15 on aarch64 and pulseaudio, only rebooting helps :/

**Comment by pelwell** [comment]
How flaky is the Bluetooth connection? And on which Pi (`tail -3 /proc/cpuinfo`)? I've had a 4B running for hours on the 64-bit kernel, but early Pi 3Bs are lacking the flow control signals necessary to avoid dropping Bluetooth data under load.

**Comment by bjo81** [comment]
I've switched from aarch64 mainline to the rpi4-aarch64-kernel on a Pi 3B 1.2 and it works fine now (except under high load).

**Comment by pelwell** [comment]
A downstream patch that was present in rpi-5.10.y to avoid UART FIFO overflow is not in rpi-5.15.y, but I believe the patch is no longer necessary because of a change to the usage of the port spinlock.

**Comment by mminelli** [comment]
Sorry for the late reply: my system is a Pi3 B with
```
$ uname -a
Linux alarmpi 5.10.79-1-raspberrypi-ARCH #1 SMP Mon Nov 15 21:41:38 UTC 2021 armv7l GNU/Linux
```

```
$ pacman -Q | grep blue
bluez 5.62-1
bluez-libs 5.62-1
bluez-tools 0.2.0-5
bluez-utils-compat 5.54-1
pulseaudio-bluetooth 15.0-1
python-pybluez 0.23-2
```
I don't really use it that often via bluetooth, but haven't noticed any "flakiness".

**Comment by dontech** [comment]
Hello all,

I have been using the nice "btreset" script extensively to get around some annoying drops and other problems.

However, now i have a Raspberry PI Zero 2 W which is not covered by the recovery script, and does not work.

Does anyone know how to update the script to cover this?

How was the original pin numbers extracted (and the VCIO address)?

**Comment by dontech** [comment]
OK figured it out for RPI Zero 2 W:

The reset line is still connected via direct GPIO, but its moved from GPIO45->GPIO42

so its:

raspi-gpio set 42 op dl
sleep 1
raspi-gpio set 42 op dh

Now it works!

**Comment by wtangofoxtrot** [comment]
running the 5.15.61-v7l+ kernel and seeing this issue on several pi 3/4s that i use for BLE/BT tracking around the house (https://github.com/mKeRix/room-assistant/issues/1158). Only recourse so far has been to reboot the pi when hci0 goes away
```
pi@pi-office:~ $ hcitool dev
Devices:
pi@pi-office:~ $ hciconfig hci0 down
pi@pi-office:~ $ hciconfig hci0 up
Can't init device hci0: Connection timed out (110)
```

**Comment by guma72** [comment]
I still have a similar issue on Pi 4b.

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

pi@raspberrypi:~ $ cat /proc/device-tree/model
Raspberry Pi 4 Model B Rev 1.1

pi@raspberrypi:~ $ strings /lib/firmware/brcm/BCM4345C0.hcd | grep Raspberry
&BCM43455 37.4MHz Raspberry Pi 3+-0190

None of the proposed ways of resetting works for me - reboot is needed. The connection drops after few minutes to few hours.

**Comment by sai-kiran-y** [comment]
Hi,

Did anyone find the reason for the hardware error 0x00 and any possible work around, for the same? I am randomly facing this issue, on another BLE module though.

Thanks,
Sai Kiran.

**Comment by Nicceboy** [comment]
Similar problem.

Bluetooth completely freezes after some hours. 

The workload attempts to capture Bluetooth LE advertising packets of nearby devices and nothing else. 

Versions:
```sh
uname -a
Linux raspberrypi 6.6.62+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux

strings /lib/firmware/brcm/BCM4345C0.hcd | grep Raspberry
&BCM43455 37.4MHz Raspberry Pi 3+-0190
```

Kernel log might have something useful 

```bash
[11816.559706] Unable to handle kernel NULL pointer dereference at virtual address 0000000000000000
[11816.559769] Mem abort info:
[11816.559784]   ESR = 0x0000000096000005
[11816.559802]   EC = 0x25: DABT (current EL), IL = 32 bits
[11816.559830]   SET = 0, FnV = 0
[11816.559847]   EA = 0, S1PTW = 0
[11816.559863]   FSC = 0x05: level 1 translation fault
[11816.559884] Data abort info:
[11816.559898]   ISV = 0, ISS = 0x00000005, ISS2 = 0x00000000
[11816.559919]   CM = 0, WnR = 0, TnD = 0, TagAccess = 0
[11816.559941]   GCS = 0, Overlay = 0, DirtyBit = 0, Xs = 0
[11816.559963] user pgtable: 4k pages, 39-bit VAs, pgdp=0000000004400000
[11816.559989] [0000000000000000] pgd=0000000000000000, p4d=0000000000000000, pud=0000000000000000
[11816.560038] Internal error: Oops: 0000000096000005 [#1] PREEMPT SMP
[11816.560066] Modules linked in: rfcomm snd_seq_dummy snd_hrtimer snd_seq snd_seq_device cmac algif_hash aes_arm64 aes_generic algif_skcipher af_alg bnep brcmfmac_wcc binfmt_misc brcmfmac brcmutil hci_uart cfg80211 btbcm bluetooth bcm2835_codec(C) bcm2835_isp(C) bcm2835_v4l2(C) v4l2_mem2mem bcm2835_mmal_vchiq(C) videobuf2_vmalloc videobuf2_dma_contig ecdh_generic videobuf2_memops ecc videobuf2_v4l2 raspberrypi_hwmon rfkill videodev libaes i2c_bcm2835 videobuf2_common mc raspberrypi_gpiomem vc_sm_cma(C) snd_bcm2835(C) i2c_dev ledtrig_pattern fuse dm_mod ip_tables x_tables ipv6 vc4 snd_soc_hdmi_codec snd_soc_core snd_compress snd_pcm_dmaengine snd_pcm snd_timer snd drm_display_helper drm_dma_helper drm_kms_helper drm drm_panel_orientation_quirks backlight cec uio_pdrv_genirq uio
[11816.560591] CPU: 2 PID: 1250 Comm: kworker/u13:2 Tainted: G         C         6.6.62+rpt-rpi-v8 #1  Debian 1:6.6.62-1+rpt1
[11816.560636] Hardware name: Raspberry Pi 3 Model B Plus Rev 1.3 (DT)
[11816.560662] Workqueue: hci0 hci_rx_work [bluetooth]
[11816.560890] pstate: 20000005 (nzCv daif -PAN -UAO -TCO -DIT -SSBS BTYPE=--)
[11816.560923] pc : eir_has_uuids+0x1a0/0x2b8 [bluetooth]
[11816.561117] lr : mgmt_device_found+0x440/0x718 [bluetooth]
[11816.561309] sp : ffffffc08113bab0
[11816.561327] x29: ffffffc08113bab0 x28: 00000000ffffffba x27: 0000000000000000
[11816.561371] x26: 0000000000000080 x25: 0000000000000001 x24: 000000000000007f
[11816.561413] x23: 0000000000000000 x22: 000000000000001e x21: ffffff8002517495
[11816.561455] x20: ffffff800251748e x19: ffffff80031b6000 x18: 0000000000000000
[11816.561498] x17: ffffffa06ceee000 x16: ffffffdfcdae6110 x15: 0000000000000000
[11816.561540] x14: 000000000000000c x13: ffffffdfcdd5cc38 x12: 00000000fdae8b7a
[11816.561582] x11: ffffff8002517497 x10: 0000000000000012 x9 : 0000000000000000
[11816.561623] x8 : 0000000000000011 x7 : 0000000000000010 x6 : 0000000000000020
[11816.561664] x5 : 6e400001b5a3f393 x4 : 0000000000000000 x3 : 0000000000000000
[11816.561705] x2 : 0000000000000001 x1 : 000000000000001e x0 : ffffff8002517495
[11816.561747] Call trace:
[11816.561765]  eir_has_uuids+0x1a0/0x2b8 [bluetooth]
[11816.561958]  mgmt_device_found+0x440/0x718 [bluetooth]
[11816.562154]  process_adv_report.part.0+0x1f4/0x658 [bluetooth]
[11816.562350]  hci_le_adv_report_evt+0x1b4/0x1d0 [bluetooth]
[11816.562540]  hci_le_meta_evt+0xbc/0x190 [bluetooth]
[11816.562730]  hci_event_packet+0x1b0/0x4f8 [bluetooth]
[11816.562923]  hci_rx_work+0xac/0x3d0 [bluetooth]
[11816.563113]  process_one_work+0x148/0x3b8
[11816.563147]  worker_thread+0x32c/0x450
[11816.563173]  kthread+0x11c/0x128
[11816.563207]  ret_from_fork+0x10/0x20
[11816.563244] Code: 14000004 91004084 eb07009f 54000180 (f9400085)
[11816.563273] ---[ end trace 0000000000000000 ]---
```

**Comment by suezz** [comment]
I also have bluetooth dropping on Pi4B, bnep0 tethering:

- Bluetooth connected to miniuart 921600 noflow,:
   no drop works ok
 
- Bluetooth connected to PL011 3000000 flow but also at 921600 noflow:
  random drop with hardware error 0x00, simple wget download seem more stable, browser traffic cause drop in few minute 
  or second
