### ISSUE TITLE
Stuttering text-to-speech since MMAP update to bcm2835 driver

### ISSUE THREAD

**Issue by cromarty** [raspberrypi/linux#304]
Since about a month ago, when the MMAP change was made to the sound driver, text-to-speech with espeak is now almost unusable.  Speech is very broken and slows down when speaking long strings, including dmesg

Have deleted /etc/asound.conf.  No help

**Comment by yusufk** [comment]
10 second sound delay, plays for about 10 seconds and then begins to drag out audio

**Comment by cromarty** [comment]
I have now discovered that using pulseaudio with espeak instead of 
portaudio solves this

On 17/01/2014 16:38, Yusuf Kaka wrote:

> 10 second sound delay, plays for about 10 seconds and then begins to 
> drag out audio
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/raspberrypi/linux/issues/304#issuecomment-32621396.

## 

Michael A. Ray
Analyst/Programmer
Witley, Surrey, South-east UK

Ham Radio Call-sign: G4XBF, licensed since 1982

Don't just sit there, learn something

Raspberry VI:
http://www.raspberryvi.org/
NVDA, the best free screen-reader in the world:
http://www.nvda-project.org/

**Comment by giddyhup** [comment]
It seems to have returned. I noticed a similar issue with recent firmwares.

I gave this solution (http://www.scribd.com/doc/232827505/Audio-Errors-With-Espeak-Raspberry-Pi-Stack-Exchange) a try, changing the front speaker assignment but it didn't help (of course I reloaded the settings with `sudo /usr/sbin/alsa force-reload`).

**Comment by Ruffio** [comment]
@cromarty according to your last statement (17 Jan 2014) this issue appears to have been fixed. Please close this issue if that is the case.

**Comment by cromarty** [comment]
No it hasn't been fixed.  Still happening.

On 28/07/2016 09:36, Rasmus Christiansen wrote:

> @cromarty according to your last statement (17 Jan 2014) this issue appears to have been fixed. Please close this issue if that is the case.
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/raspberrypi/linux/issues/304#issuecomment-235833895

## 

Michael A. Ray
Analyst/Programmer
Witley, Surrey, South-east UK

Eyes Free Linux:
http://eyesfreelinux.ninja/

Raspberry VI:
http://www.raspberryvi.org/

**Comment by muesli4** [comment]
I did work for some time, then it got worse and sometimes it's just one continuous buzzing sound.

**Comment by JamesH65** [comment]
I believe the sound system (Linux side) has changed since the last comment. Does this still happen?

This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.

**Comment by cromarty** [comment]
I recently confirmed that the stuttering no longer happens.

I am assuming also then that the kernel oops caused by null pointers
being passed to the kernel by the vchiq has also stopped.

Mike


On 27/06/2018 16:28, James Hughes wrote:
> I believe the sound system (Linux side) has changed since the last comment. Does this still happen?
> 
> This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.
> 


-- 
Michael A. Ray
Analyst/Programmer
Witley, Surrey, South-east UK

"Perfection is achieved, not when there is nothing more to add, but when
there is nothing left to take away." -- A. de Saint-Exupery

https://cromarty.github.io/
http://eyesfreelinux.ninja/
http://www.raspberryvi.org/

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
