### ISSUE TITLE
vcgencmd causing kernel WARNINGs

### ISSUE THREAD

**Issue by srcshelton** [raspberrypi/linux#361]
I have rpi-montior (http://rpi-experiences.blogspot.fr/) regularly invoking 'vcgencmd' to determine the core voltage and to output the amount of memory assigned to ARM and VC respectively... and this works, for about two hours.

After roughly this period, vcgencmd continues to output the appropriate data, but each invocation generates a `dmesg` entry similar to:

```
[17396.823193] ------------[ cut here ]------------
[17396.823249] WARNING: at /usr/portage/local/raspberrypi/src/kernel-3.10.y/fs/proc/generic.c:356 proc_register+0xe0/0x148()
[17396.823265] proc_dir_entry 'clients/8388' already registered
[17396.823276] Modules linked in: loop ipv6 cpufreq_ondemand nls_iso8859_15 nls_cp850 vfat fat raid1 md_mod spi_bcm2708 i2c_bcm2708 i2c_core cachefiles fscache bcm2708_wdog bcm2835_thermal thermal_sys freq
_table bcm2708_rng rng_core dmaer_master
[17396.823371] CPU: 0 PID: 8388 Comm: vcgencmd Tainted: G        W    3.10.7-srcs #5
[17396.823435] [<c0012ef0>] (unwind_backtrace+0x0/0xe0) from [<c0010788>] (show_stack+0x10/0x14)
[17396.823477] [<c0010788>] (show_stack+0x10/0x14) from [<c001f9c8>] (warn_slowpath_common+0x4c/0x68)
[17396.823506] [<c001f9c8>] (warn_slowpath_common+0x4c/0x68) from [<c001fa64>] (warn_slowpath_fmt+0x2c/0x3c)
[17396.823536] [<c001fa64>] (warn_slowpath_fmt+0x2c/0x3c) from [<c0100730>] (proc_register+0xe0/0x148)
[17396.823566] [<c0100730>] (proc_register+0xe0/0x148) from [<c0100878>] (proc_mkdir_data+0x48/0x68)
[17396.823594] [<c0100878>] (proc_mkdir_data+0x48/0x68) from [<c02beaf8>] (vchiq_open+0xc4/0x1a8)
[17396.823623] [<c02beaf8>] (vchiq_open+0xc4/0x1a8) from [<c00b5a5c>] (chrdev_open+0x170/0x194)
[17396.823660] [<c00b5a5c>] (chrdev_open+0x170/0x194) from [<c00b0248>] (do_dentry_open.isra.12+0x180/0x240)
[17396.823693] [<c00b0248>] (do_dentry_open.isra.12+0x180/0x240) from [<c00b032c>] (finish_open+0x24/0x38)
[17396.823729] [<c00b032c>] (finish_open+0x24/0x38) from [<c00be844>] (do_last.isra.45+0x934/0xb28)
[17396.823760] [<c00be844>] (do_last.isra.45+0x934/0xb28) from [<c00beae0>] (path_openat+0xa8/0x404)
[17396.823788] [<c00beae0>] (path_openat+0xa8/0x404) from [<c00bf0f0>] (do_filp_open+0x2c/0x78)
[17396.823820] [<c00bf0f0>] (do_filp_open+0x2c/0x78) from [<c00b119c>] (do_sys_open+0xe4/0x170)
[17396.823850] [<c00b119c>] (do_sys_open+0xe4/0x170) from [<c000d7c0>] (ret_fast_syscall+0x0/0x30)
[17396.823865] ---[ end trace d63189854f08f312 ]---
```

I'll can raise this as a firmware issue - but no matter what user-space is doing, I wouldn't anticipate it causing the kernel to fill my logs with warnings :(

**Comment by popcornmix** [comment]
I'm assuming this only affects 3.10 kernel?
Does it occur with 3.9 or 3.6 kernels?

3.10 kernel is very much experimental, and comes with no guarantees.
Due to api changes in procfs, bits of our drivers have been commented out. It possible this hasn't been done correctly in the call stack shown.

**Comment by srcshelton** [comment]
I can check whether the issue also manifests on 3.9.y or 3.6.y this evening... I've only adopted RPi-Monitor since I was using 3.10.y, so haven't tried earlier versions.

**Comment by ajs124** [comment]
I'm experiencing the same issue in archlinux (3.10 kernel) with a php script that regularly calls "vcgencmd measure_temp".

**Comment by popcornmix** [comment]
I think I've fixed it. rpi-3.10.y is rebased onto 3.10.9 and the "bcm2708 vchiq driver" commit has been adjusted to stub out more of the procfs calls.

**Comment by ajs124** [comment]
This still occurs with archlinux arm's core/linux-raspberrypi-latest at version 3.10.9-1.
uname -a returns "Linux [hostname] 3.10.9-1-ARCH+ #1 PREEMPT Sat Aug 24 05:18:52 CDT 2013 armv6l GNU/Linux"
Is there a way for me to check if this includes the relevant commits?

**Comment by popcornmix** [comment]
If you still get the error, and have no evidence that the patch has been applied, then there's a good chance it hasn't.
Can you post the backtrace? If it stil looks identical, then I think the patch can't have been applied, as vchiq_open doesn't call proc_mkdir_data.

**Comment by ajs124** [comment]
```
[ 3176.553240] ------------[ cut here ]------------
[ 3176.553313] WARNING: at fs/proc/generic.c:356 proc_register+0xac/0x14c()
[ 3176.553329] proc_dir_entry 'clients/10373' already registered
[ 3176.553340] Modules linked in: bridge stp llc arc4 rt2800usb rt2800lib rt2x00usb rt2x00lib mac80211 cfg80211 crc_ccitt evdev leds_gpio led_class i2c_bcm2708 spi_bcm2708 snd_bcm2835 snd_pcm snd_page_alloc snd_timer snd nf_conntrack_ftp nf_conntrack bcm2708_rng rng_core ipv6
[ 3176.553462] CPU: 0 PID: 10373 Comm: vcgencmd Tainted: G        W    3.10.9-1-ARCH+ #1
[ 3176.553531] [<c0013f28>] (unwind_backtrace+0x0/0xf0) from [<c0011284>] (show_stack+0x10/0x14)
[ 3176.553580] [<c0011284>] (show_stack+0x10/0x14) from [<c00233bc>] (warn_slowpath_common+0x4c/0x68)
[ 3176.553615] [<c00233bc>] (warn_slowpath_common+0x4c/0x68) from [<c002346c>] (warn_slowpath_fmt+0x30/0x40)
[ 3176.553651] [<c002346c>] (warn_slowpath_fmt+0x30/0x40) from [<c0151db8>] (proc_register+0xac/0x14c)
[ 3176.553684] [<c0151db8>] (proc_register+0xac/0x14c) from [<c0151f4c>] (proc_mkdir_data+0x44/0x6c)
[ 3176.553731] [<c0151f4c>] (proc_mkdir_data+0x44/0x6c) from [<c04987b8>] (vchiq_open+0xa4/0x1ac)
[ 3176.553766] [<c04987b8>] (vchiq_open+0xa4/0x1ac) from [<c00fa50c>] (chrdev_open+0xbc/0x1a8)
[ 3176.553806] [<c00fa50c>] (chrdev_open+0xbc/0x1a8) from [<c00f4788>] (do_dentry_open+0x1ec/0x264)
[ 3176.553837] [<c00f4788>] (do_dentry_open+0x1ec/0x264) from [<c00f4a94>] (finish_open+0x34/0x4c)
[ 3176.553880] [<c00f4a94>] (finish_open+0x34/0x4c) from [<c01037f4>] (do_last.isra.21+0x530/0xc64)
[ 3176.553915] [<c01037f4>] (do_last.isra.21+0x530/0xc64) from [<c0103fd4>] (path_openat+0xac/0x48c)
[ 3176.553947] [<c0103fd4>] (path_openat+0xac/0x48c) from [<c0104670>] (do_filp_open+0x2c/0x80)
[ 3176.553983] [<c0104670>] (do_filp_open+0x2c/0x80) from [<c00f5970>] (do_sys_open+0xe4/0x174)
[ 3176.554018] [<c00f5970>] (do_sys_open+0xe4/0x174) from [<c000db80>] (ret_fast_syscall+0x0/0x30)
[ 3176.554035] ---[ end trace ad61f6e6ca18d990 ]---
```

Ok, I see the proc_mkdir_data in there. Sorry for the noise… I'll build a fresh kernel from git and report back.

**Comment by ajs124** [comment]
Seems fixed for me, can you confirm that @srcshelton?

**Comment by srcshelton** [comment]
Yup - looks good so far, no warnings in the past 3 hours since the kernel finished recompiling.  I'll update and close tomorrow if things continue to be okay.

**Comment by popcornmix** [comment]
@srcshelton 
Okay to close?

**Comment by srcshelton** [comment]
Yup - all good, thanks :)
