### ISSUE TITLE
RPi 2 doesn't boot on linux-raspberrypi 5.10.31-2 when connected with HDMI

### ISSUE THREAD

**Issue by nightBulb** [raspberrypi/linux#4299]
**Describe the bug**
Raspberry Pi 2 fails to boot when using linux-raspberrypi **5.10.31-2** with HDMI connected.
```
Good Kernel : Linux 5.10.31-1 

Bad Kernel: Linux 5.10.31-2  and Linux 5.10.31-3
```

**To reproduce**
Reboot `R Pi 2` after update to linux-raspberrypi 5.10.31-2 
with the the RPi 2 connected via HDMI to a screen

**Expected behaviour**
System to boot

**Actual behaviour**
Raspberry Pi 2 fails to boot when using linux-raspberrypi `5.10.31-2` with RPi 2 connected to a screen with HDMI.

**System**

* Which model of Raspberry Pi? 
`R Pi 2`, as per https://github.com/raspberrypi/linux/issues/4299#issuecomment-823909548 it affects `RPi 3` as well

* Which OS and version (`cat /etc/rpi-issue`)?
```
Arch Linux ARM (latest)

 (Don't have rpi-issue file)
```

* Which firmware version (`vcgencmd version`)?
```
Apr 12 2021 15:54:06 
Copyright (c) 2012 Broadcom
version 0227a0840ee8c94294cf3b2c4b2d42031a58f05a (clean) (release) (start)
```

* Which kernel version (`uname -a`)?
 ```
Linux rpi 5.10.31-1-ARCH #1 SMP Mon Apr 19 13:33:01 UTC 2021 armv7l GNU/Linux

```

**Logs**
(Unable to get dmesg when boot fails)
dmesg log when system boots -> https://github.com/raspberrypi/linux/issues/4299#issuecomment-823666132

photo of boot screen when boot fails -> https://github.com/raspberrypi/linux/issues/4299#issuecomment-823692455

dmesg with good kernel in disconnected state -> https://github.com/raspberrypi/linux/issues/4299#issuecomment-823986434

**Additional context**
```
Note 1: 
Linux 5.10.31-1 boots successfully with and without HDMI connected.

Linux 5.10.31-2 boot fails when HDMI screen is connected.
Linux 5.10.31-2 boot succeeds when HDMI is **disconnected**.

--------------------
Note 2:
The Bootloader manages to switch to systemd (I think)
It is during systemD initialization that HDMI screen goes blank.
 
It feels like the boot gets stuck right before the login prompt is supposed to appear.
(No network, although I think I am able to see [  ok  ]  for network service. )

```

**Comment by nightBulb** [comment]
dmesg output:

1. When boot succeeds with bad kernel ( DISCONNECTED HDMI ) linux 5.10.31-2
[dmesg-2021-04-21-bad-kernel-log.txt](https://github.com/raspberrypi/linux/files/6347124/dmesg-2021-04-21-bad-kernel-log.txt)

2. When boot succeeds with good kernel Linux ( CONNECTED HDMI ) 5.10.31-1
[dmesg-2021-04-21-good-kernel-log.txt](https://github.com/raspberrypi/linux/files/6347127/dmesg-2021-04-21-good-kernel-log.txt)

3. Couldn't get the failure ( linux 5.10.31-2, HDMI Connected)  `dmesg` output as no login prompt

<hr />
Colored variants of above logs

```
$ dmesg --color=always
```

[dmesg-2021-04-21-bad-kernel-log-colored.txt](https://github.com/raspberrypi/linux/files/6347126/dmesg-2021-04-21-bad-kernel-log-colored.txt)

[dmesg-2021-04-21-good-kernel-log-colored.txt](https://github.com/raspberrypi/linux/files/6347128/dmesg-2021-04-21-good-kernel-log-colored.txt)

**Comment by nightBulb** [comment]
This is the last thing that happens when booting with Linux 5.10.31-2 
(bad kernel) connected via HDMI to the screen.

![IMG_20210421_042256462_BURST073](https://user-images.githubusercontent.com/13586745/115480048-55d0a380-a267-11eb-811a-44e2b1eec593.jpg)

**Comment by henkv1** [comment]
Same issue here on RPi3.
The system crashes when kms refreshes the screen. The issue does not occur when fkms is used. So this is probably a bug in the new vc4 code.

**Comment by pelwell** [comment]
Can one of you provide a dmesg log for the good kernel in the disconnected state?

**Comment by popcornmix** [comment]
I can reproduce this (on Pi3+). No panic out of uart when it hangs. Presumably related to clock changes.

**Comment by popcornmix** [comment]
Yes, 9e081a7bf69c75d5e9cb05add07eaf4cb4ee4dc9 seems to be first commit which hangs. It's okay on Pi4.

**Comment by nightBulb** [comment]
@pelwell This is the `dmesg` for good kernel (Linux 5.10.31-1 ) in HDMI disconnected state
[dmesg-2021-04-21-3-good-kernel-disconnected.txt](https://github.com/raspberrypi/linux/files/6350397/dmesg-2021-04-21-3-good-kernel-disconnected.txt)

<hr />

Same dmesg with `dmesg --color=always`

[dmesg-2021-04-21-3-good-kernel-disconnected-colored.txt](https://github.com/raspberrypi/linux/files/6350398/dmesg-2021-04-21-3-good-kernel-disconnected-colored.txt)

**Comment by pelwell** [comment]
Thanks. Now that popcornmix has reproduced the problem we shouldn't need any more info.

**Comment by popcornmix** [comment]
I've pushed a new kernel to rpi-update that should hopefully resolve this. Can you test?

**Comment by nightBulb** [comment]
@popcornmix Problem still persists.

Unable to complete boot with linux 5.10.31-3 while HDMI is connected.

Boot only succeeds with it disconnected.

**Comment by popcornmix** [comment]
With hdmi disconnected what does `uname -a` report?

**Comment by nightBulb** [comment]
@popcornmix  Linux rpi 5.10.31-3-ARCH #1 SMP Wed Apr 21 14:04:34 UTC 2021 armv7l GNU/Linux

**Comment by popcornmix** [comment]
You aren't using rpi-update kernel, so I'm unsure what commits are in there.
From the timestamp of your kernel, it doesn't look like you'll have the commit that fixes it.
```
commit 01a6d727b407ed064bdd72e3a6611101102a2228
Author: Dom Cobley <popcornmix@gmail.com>
Date:   Wed Apr 21 15:15:42 2021 +0100

    vc4/drm: hdmi: Handle case when bvb clock is null
    
    Pi2/3 have no bvb clock but want the other clocks to remain enabled here
    
    See: https://github.com/raspberrypi/linux/issues/4299
    Signed-off-by: Dom Cobley <popcornmix@gmail.com>
```

**Comment by popcornmix** [comment]
This is booting with hdmi output on a pi3 for me:
```
pi@b3plus:~ $ uname -a
Linux domnfs 5.10.31-v7+ #62 SMP Wed Apr 21 15:41:57 BST 2021 armv7l GNU/Linux
```

**Comment by nightBulb** [comment]
@graysky2 could you please update the linux kernel to commit 01a6d727b407ed064bdd72e3a6611101102a2228

**Comment by graysky2** [comment]
@nightBulb - Building https://github.com/raspberrypi/linux/commit/203f70487548714de96bd3f530c8f8a6d558971e and will test/push if all is well.

**Comment by nightBulb** [comment]
@graysky2 Thanks  :smile: :+1:

**Comment by graysky2** [comment]
https://github.com/archlinuxarm/PKGBUILDs/commit/c9ee7290871028d2135656ae9ce4e06ada0d0e49

**Comment by nightBulb** [comment]
I just tested `Linux rpi 5.10.31-4-ARCH #1 SMP Wed Apr 21 17:54:17 UTC 2021 armv7l GNU/Linux`

and can confirm the problem is fixed, and the system is booting with HDMI connected. :smile:  :+1: 

Thanks :+1: :+1: and Kudos :1st_place_medal:   everyone. 

I can now recommend we close this bug.
