### ISSUE TITLE
After upgrade to 3.12.20+ - ipv6 privacy extensions stopped working

### ISSUE THREAD

**Issue by LeffeG** [raspberrypi/linux#612]
# zcat /proc/config.gz | fgrep CONFIG_IPV6_PRIVACY
# CONFIG_IPV6_PRIVACY is not set

**Comment by daincredibleholg** [comment]
Any updates on this?

**Comment by LeffeG** [comment]
No, but i got a tip on the #raspbian irc channel to install the
http://www.raspbian.org/ kernel instead, so i did that and that kernel has
ipv6 privacy extensions enabled by default.
1. sudo apt-get update
2. sudo apt-get install linux-image-rpi-rpfv
3. In boot/config.txt append this at end of file , or it will boot the
default "Foundation kernel"
************\* SNIP ***********************

# Set params for "raspbian debian-style kernel" boot

kernel=vmlinuz-<version>-rpi
initramfs initrd.img-<version>-rpi followkernel
************\* SNIP ***********************
4: reboot
5: login
6: apt-get install linux-headers-rpi-rpfv

Works excellent.

/Leffe

2014-06-13 14:18 GMT+02:00 Holger notifications@github.com:

**Comment by LeffeG** [comment]
1. is optional.

2014-06-13 23:28 GMT+02:00 Leif Gustafsson leffeg65@gmail.com:

**Comment by popcornmix** [comment]
CONFIG_IPV6_PRIVACY added to source tree. Will be in next firmware update.

**Comment by popcornmix** [comment]
This should be in latest firmware. Can you rpi-update and test?

**Comment by daincredibleholg** [comment]
I did the update. Now, I can do the setting but no IPv6 address is used. I checked it twice - the module ipv6 is loaded and all the devices (lo and eth0) have the local address, but no global and temp address are available and no ping6 is possible. Any ideas?

**Comment by popcornmix** [comment]
I can't help with your network setup, perhaps someone else knows more.
As far as this github issue goes, it should be resolved:

```
$ zcat /proc/config.gz | grep PRIVACY
CONFIG_IPV6_PRIVACY=y
```

**Comment by daincredibleholg** [comment]
Actually, it is not about my local setup - it looks like the IPv6 stack is still broken (my other maschines work fine with IPv6). But I will open a new ticket for it. Thanks for the fix.

**Comment by LeffeG** [comment]
No, it's still not updated:

# uname -a

Linux rspi3 3.12.20+ #687 PREEMPT Fri May 30 16:39:11 BST 2014 armv6l
GNU/Linux

# zcat /proc/config.gz | grep PRIVACY

# CONFIG_IPV6_PRIVACY is not set

ipv6 works ok but not temporary dynamic addresses.

2014-06-16 19:46 GMT+02:00 Holger notifications@github.com:

**Comment by popcornmix** [comment]
@LeffeG 
I don't think your update worked (in fact you are 8 firmware versions behind).
Can you compare your kernel to:
https://github.com/Hexxeh/rpi-firmware/raw/master/kernel.img

What did rpi-update report? I assume you have rebooted?
Can you run:

```
sudo rpi-update bfd37013c701f10c6df585346ee1d3d3bdf88b3b
```

**Comment by LeffeG** [comment]
no i didn't find rpi-update on the system so i will stick to use apt-get
update, apt-get upgrade since rpi-update can conflict with the others...

2014-06-16 23:31 GMT+02:00 popcornmix notifications@github.com:

**Comment by LeffeG** [comment]
http://www.raspberrypi.org/forums/viewtopic.php?f=91&t=58963

"That's pretty much it. I would change that to "Only run rpi-update if you
know you need a specific build of the firmware or if you were asked to do
so by Dom.""

2014-06-16 23:47 GMT+02:00 Leif Gustafsson leffeg65@gmail.com:

**Comment by popcornmix** [comment]
I feel if you open a github issue to add a new feature, then it is appropriate to run rpi-update to be able to test that feature.

As it seems to have caused a problem for @daincredibleholg it will be removed before the next apt-get firmware is updated unless there are some positive reports.

**Comment by LeffeG** [comment]
I do not want to add a new feature as the feature was working before the
upgrade via apt-get update, apt-get upgrade.
I would like to run a stable supportet release and not the latest unstable
code.
Can you tell me what packages will get updated with rpi-update and how to
get back to the stable version if anything else stops working?

2014-06-17 0:18 GMT+02:00 popcornmix notifications@github.com:

**Comment by asb** [comment]
rpi-update will replace files in the raspberrypi-firmware family of packages. Do downgrade you could either use rpi-update to go back to a specific commit id, or do `sudo apt-get install --reinstall libraspberrypi-bin libraspberrypi-dev libraspberrypi-doc libraspberrypi0 raspberrypi-bootloader`

**Comment by grigorig** [comment]
You still may need to enable the privacy extensions for the ethernet interface. Adding support in the kernel doesn't automatically enable them. You can do that with /etc/network/interfaces, see the man page interfaces(5).

**Comment by LeffeG** [comment]
After the latest apt-get update, apt-get install it was enabled again. Now
it's working ok on:

# uname -a

Linux rspi3 3.12.22+ #691 PREEMPT Wed Jun 18 18:29:58 BST 2014 armv6l
GNU/Linux

2014-06-17 16:33 GMT+02:00 Grigori Goronzy notifications@github.com:

**Comment by popcornmix** [comment]
Okay to close then?

**Comment by daincredibleholg** [comment]
I still have the problems - any ideas how to dig deeper on that problem? I just made a apt-get update && apt-get dist-upgrade + reboot and there is still no IPv6 connectivity.

_Edit_: Sorry, wrong issue. Yeah, security extensions should be available now.
