### ISSUE TITLE
mouse in slow motion only

### ISSUE THREAD

**Issue by gkreidl** [raspberrypi/linux#642]
The latest change in mouse polling frequency has reduced mouse speed and made it almost unusable. I'm using a wireless (RF) mouse / keyboard combo.

**Comment by popcornmix** [comment]
Does adding:

```
usb_hid.mousepoll=0
```

to cmdline.txt fix it?


EDIT: Note: this should actually be `usbhid.mousepoll=0` rather than `usb_hid.mousepoll=0`

**Comment by gkreidl** [comment]
no, it got worse (subjectively), it's more drawing behind, mouse pointer is still moving when I stop moving the mouse

**Comment by popcornmix** [comment]
How about:

```
usb_hid.mousepoll=1
```

**Comment by gkreidl** [comment]
no change, I need three long movements with the mouse to cross the screen

**Comment by popcornmix** [comment]
Can you try this kernel:
https://dl.dropboxusercontent.com/u/3669512/temp/kernel.img

and add usb_hid.mousepoll=0

**Comment by gkreidl** [comment]
same as before.

**Comment by popcornmix** [comment]
What about this:
https://dl.dropboxusercontent.com/u/3669512/temp/kernel2.img

(rename to kernel.img) wit usb_hid.mousepoll removed from command line.

**Comment by gkreidl** [comment]
That's working!!!!!

**Comment by popcornmix** [comment]
Can you test with that kernel:
usb_hid.mousepoll=0
and
usb_hid.mousepoll=1

and report if they work?

**Comment by gkreidl** [comment]
it's working with both settings ... and without

**Comment by gkreidl** [comment]
has this been fixed meanwhile or does it return if I run rpi-update? I'm still using the kernel2.img you sent me.

**Comment by popcornmix** [comment]
Ah - usb_hid.mousepoll should be usbhid.mousepoll=0

First with current setup (and fast mouse) what does:

```
cat /sys/module/usbhid/parameters/mousepoll
```

report?

Can you try rpi-update, and then replace kernel with:
https://dl.dropboxusercontent.com/u/3669512/temp/kernel3.img

I expect that will still be slow. Now add usbhid.mousepoll=0 and it should become quick again.

**Comment by gkreidl** [comment]
cat /sys/module/usbhid/parameters/mousepoll gives
0
with my current kernel (fast mouse)
Now I'll go on with your suggestions ...

**Comment by gkreidl** [comment]
after rpi-update and replacing the kernel it was slow again
after adding usbhid.mousepoll=0 to the command line it's working again.
Hope that helps to enter it into the release. There should be some kind of information in the forum about the command line option if people experience the same problem.

**Comment by popcornmix** [comment]
Okay, future firmwares will behave like this, so you should add usbhid.mousepoll=0 to get fast mouse.

We'll need to keep an eye on how many devices behave like yours.
It feels like incorrect behaviour - if you poll a mouse less often, it should just report larger increments, not move slower, but I'd be interested to hear if anyone has more knowledge on this subject.

**Comment by gkreidl** [comment]
Yes, it is device dependent; I've also tested with an air mouse and that worked well.

**Comment by popcornmix** [comment]
Okay, latest firmware update should support "usbhid.mousepoll=0". Run rpi-update and test.

**Comment by gkreidl** [comment]
Done. Works. I'll close the issue.

**Comment by beta-tester** [comment]
today i got my RPi B+ and i installed the "2014-06-20-wheezy-raspbian.zip" Image, i downloaded today.
it has a kernel Version 3.12.22+ from 2014-06-18.
here my mouse is working normal as usual.

after sudo rpi-update to 3.12.25+  from 2014-07-24, i have the issue with the very slowed down mouse movements.

i tried all suggested config.txt Options, but None of them are working.
the mousepoll stays at a value of 4294967295
and the mouse is not really usable.

pi@raspberrypi ~ $ uname -a
`Linux raspberrypi 3.12.25+ #700 PREEMPT Thu Jul 24 17:51:46 BST 2014 armv6l GNU/Linux`

pi@raspberrypi ~ $ cat /sys/module/usbhid/parameters/mousepoll
`4294967295`

(edit: i deleted some of the content, because it was wrong and confusing)

**Comment by beta-tester** [comment]
oops, i should read more precisely...
i putted the option **usbhid.mousepoll=0** to **config.txt**
but i have to put the option **usbhid.mousepoll=0** to **cmdline.txt**

**Comment by asb** [comment]
Out of interest, what make/model is your mouse?

**Comment by beta-tester** [comment]
it is a wireless Keyboard-mouse-combi:
rapoo E2700; german layout; EAN: 6 943518 912875;

at boot time:

```
[    3.781772] usb 1-1.3: new full-speed USB device number 4 using dwc_otg
[    3.919473] usb 1-1.3: New USB device found, idVendor=24ae, idProduct=1001
[    3.940981] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    3.954623] usb 1-1.3: Product: Rapoo 2.4G Wireless Touch Desktop
[    3.966200] usb 1-1.3: Manufacturer: MOSART Semi.
[    3.997884] input: MOSART Semi. Rapoo 2.4G Wireless Touch Desktop  as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.0/input/input0
[    4.032156] hid-generic 0003:24AE:1001.0001: input,hidraw0: USB HID v1.10 Keyboard [MOSART Semi. Rapoo 2.4G Wireless Touch Desktop ] on usb-bcm2708_usb-1.3/input0
[    4.094582] input: MOSART Semi. Rapoo 2.4G Wireless Touch Desktop  as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.1/input/input1
[    4.142591] hid-generic 0003:24AE:1001.0002: input,hiddev0,hidraw1: USB HID v1.10 Mouse [MOSART Semi. Rapoo 2.4G Wireless Touch Desktop] on usb-bcm2708_usb-1.3/input1
```

i have two other wireless mouse-keyboard-combis that do **not** have these problems:
Logitech K400r
MSI Air Keyboard Model: AWK.02

**Comment by gkreidl** [comment]
Similar device, but not the same:

```
[127013.965781] usb 1-1.2.2: new full-speed USB device number 9 using dwc_otg
[127014.071535] usb 1-1.2.2: New USB device found, idVendor=062a, idProduct=4101
[127014.071561] usb 1-1.2.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[127014.071573] usb 1-1.2.2: Product: 2.4G Keyboard Mouse
[127014.071586] usb 1-1.2.2: Manufacturer: MOSART Semi.
[127014.082105] input: MOSART Semi. 2.4G Keyboard Mouse as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2.2/1-1.2.2:1.0/input/input12
[127014.083697] hid-generic 0003:062A:4101.000D: input,hidraw0: USB HID v1.10 Keyboard [MOSART Semi. 2.4G Keyboard Mouse] on usb-bcm2708_usb-1.2.2/input0
[127014.098977] input: MOSART Semi. 2.4G Keyboard Mouse as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2.2/1-1.2.2:1.1/input/input13
[127014.102807] hid-generic 0003:062A:4101.000E: input,hiddev0,hidraw1: USB HID v1.10 Mouse [MOSART Semi. 2.4G Keyboard Mouse] on usb-bcm2708_usb-1.2.2/input1
```

**Comment by Bleep42** [comment]
Hi Popcornmix,
Just had exactly this problem after an update and fixed it with "usbhid.mousepoll=0"
I am using a wireless keyboard and mouse from Maplin.
http://www.maplin.co.uk/p/maplin-mini-wireless-deskset-n69jx
Regards,
Kevin.

**Comment by stefanheijnen** [comment]
Same here with a Microsoft Wireless Mouse 5000. Fixed it with "usbhid.mousepoll=0".

[    2.459099] usb 1-1.2: new full-speed USB device number 4 using dwc_otg
[    2.594430] usb 1-1.2: New USB device found, idVendor=045e, idProduct=0745
[    2.603033] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    2.607881] usb 1-1.2: Product: Microsoft\xffffffc2\xffffffae 2.4GHz Transceiver v6.0
[    2.629018] usb 1-1.2: Manufacturer: Microsoft
[    2.649878] input: Microsoft Microsoft\xffffffc2\xffffffae 2.4GHz Transceiver v6.0 as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.0/input/input0
[    2.659108] hid-generic 0003:045E:0745.0001: input,hidraw0: USB HID v1.11 Keyboard [Microsoft Microsoft\xffffffc2\xffffffae 2.4GHz Transceiver v6.0] on usb-bcm2708_usb-1.2/input0
[    2.706510] input: Microsoft Microsoft\xffffffc2\xffffffae 2.4GHz Transceiver v6.0 as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.1/input/input1
[    2.728144] hid-generic 0003:045E:0745.0002: input,hidraw1: USB HID v1.11 Mouse [Microsoft Microsoft\xffffffc2\xffffffae 2.4GHz Transceiver v6.0] on usb-bcm2708_usb-1.2/input1
[    2.802103] input: Microsoft Microsoft\xffffffc2\xffffffae 2.4GHz Transceiver v6.0 as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.2/input/input2
[    2.819048] hid-generic 0003:045E:0745.0003: input,hiddev0,hidraw2: USB HID v1.11 Device [Microsoft Microsoft\xffffffc2\xffffffae 2.4GHz Transceiver v6.0] on usb-bcm2708_usb-1.2/input2

Linux werkkamer 3.12.29+ #714 PREEMPT Wed Oct 1 23:11:38 BST 2014 armv6l GNU/Linux

**Comment by matthuisman** [comment]
Same issue and fixed with usbhid.mousepoll=0 to cmdline.txt

Device:
UKB-500-RF Keyboard
http://www.pishop.co.nz/RPI-KEYB-1.html

[  174.729175] usb 1-1.4: new full-speed USB device number 6 using dwc_otg
[  174.831537] usb 1-1.4: New USB device found, idVendor=8301, idProduct=0089
[  174.831562] usb 1-1.4: New USB device strings: Mfr=0, Product=0, SerialNumber                            =0
[  174.839726] input: HID 8301:0089 as /devices/platform/bcm2708_usb/usb1/1-1/1-                            1.4/1-1.4:1.0/0003:8301:0089.0004/input/input3
[  174.840401] hid-generic 0003:8301:0089.0004: input,hidraw1: USB HID v1.10 Key                            board [HID 8301:0089] on usb-bcm2708_usb-1.4/input0
[  174.844692] input: HID 8301:0089 as /devices/platform/bcm2708_usb/usb1/1-1/1-                            1.4/1-1.4:1.1/0003:8301:0089.0005/input/input4
[  174.845454] hid-generic 0003:8301:0089.0005: input,hidraw2: USB HID v1.10 Mou                            se [HID 8301:0089] on usb-bcm2708_usb-1.4/input1

I wish there was an easier / safer way to change this option.
I don't like the thought of people mucking around with the cmdline.txt file.

Maybe a way to change via RASPI-CONFIG instead?
Seems to be getting quite common

**Comment by Lob0426** [comment]
This issue has cropped back up in 5.0.3 for the Raspberry Pi 2 B. Mouse drags in the video window. If the video is in the background the mouse is fine. As soon as the video Windows is to the front Mouse slows again.
"usbhid.mousepoll=0" or "usbhid.mousepoll=1" in cmdline.txt has no effect.

My mouse is a wired USB DELL mouse Model Number: M-UAV-DEL8

**Comment by BrainSlugs83** [comment]
This is definitely still an issue -- seems to basically happen on EVERY wireless mouse -- setting usehid.mousepoll=0 fixes it for me.  Can't you just make this automatic for known wireless mice?

I have the LuguLake optical vertical mouse GCM808 -- the wireless one (seems to be same serial as non-wireless one).

**Comment by Rashar** [comment]
Greetings. I've installed OSMC on a RPi 2 B and I don't see where I can write the sudo commands other than taking the sd card out, putting it in a wIndows of and browsing to cmdline.txt and editing it there. Is this ok because this fix still does not work for me. Logitech k400 wireless keyboard with integrated mouse pad.

**Comment by popcornmix** [comment]
Are you using NOOBS with OSMC installed or a direct install of OSMC?

**Comment by Rashar** [comment]
NOOBS.

Sent from Outlook

On Tue, Dec 29, 2015 at 3:53 AM -0800, "popcornmix" notifications@github.com wrote:

Are you using NOOBS with OSMC installed or a direct install of OSMC?

**Comment by Glasairman** [comment]
I had this slowness problem on 4.1.15-v7+  with a new wireless mouse with the chip 062a:4101 (Creative Labs). 

rpi-update fixed the problem today with usbhid.mousepoll=1 in /boot/cmdline.txt

I even had to slow down the mouse sensitivity!!  Thanks for the tip!

https://github.com/raspberrypi/linux/issues/642#

**Comment by StuartIanNaylor** [comment]
Worked for me already had the rpi-update but with a RII K12 wireless mini keyboard and trackpad it was awful until usbhid.mousepoll=0.
Still getting the 'sticky keys' syndrome where the keyboard / trackpad will just freeze though.
It something with the Pi as OK on Blingdows.

**Comment by SimonSellick** [comment]
That worked for a Tecknet X600 mouse / keyboard on a pi 3. But does anyone know what is going on here?  A wired mouse plugged in to the same USB worked perfectly, and so did the wirreless mouse when connected to a Windows box - so how does the data coming from the wireless and the optical mouse differ?

**Comment by macfree** [comment]
Not working for me, so +1 on this issue. I run Rasbpian vers 4.9.41 installed after NOOBS  2.4.4.  I tried to update cmdline.txt as attached (+reboot), but just the CPU load went down, however still laggy. Not sure how to find the boot output supplied by others here, dont know what to search for online to find it. 
I have done the sudo apt-get update/upgrade as well.
cat /sys/module/usbhid/parameters/mousepoll gives 4294967295 (same as beta-tester)

[cmdline.txt](https://github.com/raspberrypi/linux/files/1435443/cmdline.txt)

**Comment by beta-tester** [comment]
@macfree: i was watching the cmdline.txt file your attached.
your cmdline.txt file contains three separate lines with parameters.
as far as i know, it is not allowed to add line feeds/breaks in a cmdline.txt file.
try to put everythin in one single line (seperate the parameters by a space only).

**Comment by macfree** [comment]
@beta-tester: It worked like a charm! Thanks!

**Comment by mikeeve** [comment]
Still a problem with Microsoft wireless USB mouse and keyboard 2000. Used Noobs 2.4 lite, installed Raspbian. usbhid.mousepoll = 0 in cmdline.txt fixed it.

**Comment by adeelahmadk** [comment]
Issue exists for Hyundai HY-NK3000 wireless mouse-keyboard pair on Raspbian Jessie 2017-07-05 and Stretch 2017-11-29, works within a range 0 <= `usbhid.mousepoll` < 4, finally settled for `usbhid.mousepoll=1` in `/boot/cmdline.txt`

**Comment by richfelker** [comment]
I just hit this issue on a new rpi 3b+ with monoprice wireless mouse. Can anyone explain the mechanism of how `usbhid.mousepoll=0` is supposed to fix it? It *does* fix it for me, but as far as I can tell from the kernel sources, 0 is the default. Or have rpi kernels been patched to break the default or something?

**Comment by carlsmith** [comment]
Different, but related issue with SteelSeries Rival 100 mouse on Raspbian Stretch: The mouse moved fine, but clicks were ignored unless the button was held down for maybe 100 milliseconds. The `usbhid.mousepoll` thing fixed it.

**Comment by cupantae** [comment]
Same issue with cheap "Wireless Combo" from Amazon.
RPi 3B running Raspbian Stretch kernel 4.14.79-v7+
Fixed by usbhid.mousepoll=0 and reboot.

Manufacturer: MOSART Semi.
Product: 2.4G INPUT DEVICE
device idVendor=062a, idProduct=4c01

**Comment by richfelker** [comment]
Mine cited above is also MOSART Semi, idVendor=0x062a, idProduct=0x127a.

I'm still confused how usbhid.mousepoll=0 helps since it looks like that's the default in the kernel sources.

**Comment by eethas23** [comment]
> it is a wireless Keyboard-mouse-combi:
> rapoo E2700; german layout; EAN: 6 943518 912875;
> 
> at boot time:
> 
> ```
> [    3.781772] usb 1-1.3: new full-speed USB device number 4 using dwc_otg
> [    3.919473] usb 1-1.3: New USB device found, idVendor=24ae, idProduct=1001
> [    3.940981] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
> [    3.954623] usb 1-1.3: Product: Rapoo 2.4G Wireless Touch Desktop
> [    3.966200] usb 1-1.3: Manufacturer: MOSART Semi.
> [    3.997884] input: MOSART Semi. Rapoo 2.4G Wireless Touch Desktop  as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.0/input/input0
> [    4.032156] hid-generic 0003:24AE:1001.0001: input,hidraw0: USB HID v1.10 Keyboard [MOSART Semi. Rapoo 2.4G Wireless Touch Desktop ] on usb-bcm2708_usb-1.3/input0
> [    4.094582] input: MOSART Semi. Rapoo 2.4G Wireless Touch Desktop  as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.1/input/input1
> [    4.142591] hid-generic 0003:24AE:1001.0002: input,hiddev0,hidraw1: USB HID v1.10 Mouse [MOSART Semi. Rapoo 2.4G Wireless Touch Desktop] on usb-bcm2708_usb-1.3/input1
> ```
> 
> i have two other wireless mouse-keyboard-combis that do **not** have these problems:
> Logitech K400r
> MSI Air Keyboard Model: AWK.02

i am having problems with the mouse lag on K400r and microsoft keyboard 2000 and mouse 5000... any help??

**Comment by popcornmix** [comment]
@eethas23 does ``usbhid.mousepoll=0`` added to end of cmdline.txt help?

**Comment by eethas23** [comment]
I actually had to change it to 4 or 5 and seems to be ok ... But the other
issue is I am connected to a 47 inch TV and everything is so small giving
me a headache and I also increased the zoom in the browser but it doesn't
do it for every tab ?? Any tips for that ??

**Comment by popcornmix** [comment]
You may be better off choosing a lower resolution in Preferences->Screen Configuration.
But questions like this are best asked on the [forum](https://www.raspberrypi.org/forums).

**Comment by vlad0337187** [comment]
Had same problem with UKC Wireless USB keyboard / mouse pair.
Adding `usbhid.mousepoll=0` to `cmdline.txt` solved issue.
(took it from @beta-tester s message)

At first I tried adding `usb_hid.mousepoll=0` (suggested in first messages), which seems to be wrong.

Thanks.

**Comment by gwild** [comment]
usb_hid.mousepoll=0 actually did work for me on Linux raspberrypi 5.15.45-v8+ #1562 SMP PREEMPT Thu Jun 9 13:59:40 BST 2022 aarch64 GNU/Linux, but only because it's wrong and results in pi@raspberrypi:~ $ cat /sys/module/usbhid/parameters/mousepoll
4294967295
(usbhid.mousepoll=0 results in pi@raspberrypi:~ $ cat /sys/module/usbhid/parameters/mousepoll
0)
but at least the mouse is now useable.

**Comment by popcornmix** [comment]
@gwild yes, the `usbhid` vs `usb_hid` typo was mentioned in this [comment](https://github.com/raspberrypi/linux/issues/642#issuecomment-50012591).
I've also added a mention to initial comment of the correction.
