### ISSUE TITLE
BUG: workqueue leaked lock or atomic: kworker/0:2/0xffffffff/4586

### ISSUE THREAD

**Issue by marc40000** [raspberrypi/linux#944]
Hi !

I get a crash every one or two days on one of my rpis. Everything works fine but at some point, I get repeating entries multiple times in /var/log/syslog and /var/log/Messages multiple times per second:

```
Apr 26 17:17:12 gardeneast kernel: [160403.252871] BUG: workqueue leaked lock or atomic: kworker/0:2/0xffffffff/4586
Apr 26 17:17:12 gardeneast kernel: [160403.252871]      last function: od_dbs_timer
Apr 26 17:17:12 gardeneast kernel: [160403.285169] CPU: 0 PID: 4586 Comm: kworker/0:2 Tainted: G      D W      3.18.7+ #755
Apr 26 17:17:12 gardeneast kernel: [160403.313727] Workqueue: events od_dbs_timer
Apr 26 17:17:12 gardeneast kernel: [160403.327924] [<c00151fc>] (unwind_backtrace) from [<c0012710>] (show_stack+0x20/0x24)
Apr 26 17:17:12 gardeneast kernel: [160403.356381] [<c0012710>] (show_stack) from [<c0555b30>] (dump_stack+0x20/0x28)
Apr 26 17:17:12 gardeneast kernel: [160403.374797] [<c0555b30>] (dump_stack) from [<c0039d60>] (process_one_work+0x360/0x444)
Apr 26 17:17:12 gardeneast kernel: [160403.402947] [<c0039d60>] (process_one_work) from [<c003a998>] (worker_thread+0x190/0x580)
Apr 26 17:17:12 gardeneast kernel: [160403.431557] [<c003a998>] (worker_thread) from [<c003edf8>] (kthread+0xd8/0xf4)
Apr 26 17:17:12 gardeneast kernel: [160403.449926] [<c003edf8>] (kthread) from [<c000e988>] (ret_from_fork+0x14/0x20)
Apr 26 17:17:12 gardeneast kernel: [160403.469339] BUG: workqueue leaked lock or atomic: kworker/0:2/0xffffffff/4586
Apr 26 17:17:12 gardeneast kernel: [160403.469339]      last function: BlinkWorkItemCallback [8192cu]
Apr 26 17:17:12 gardeneast kernel: [160403.503255] CPU: 0 PID: 4586 Comm: kworker/0:2 Tainted: G      D W      3.18.7+ #755
Apr 26 17:17:12 gardeneast kernel: [160403.531949] Workqueue: events BlinkWorkItemCallback [8192cu]
Apr 26 17:17:12 gardeneast kernel: [160403.547943] [<c00151fc>] (unwind_backtrace) from [<c0012710>] (show_stack+0x20/0x24)
Apr 26 17:17:12 gardeneast kernel: [160403.576332] [<c0012710>] (show_stack) from [<c0555b30>] (dump_stack+0x20/0x28)
Apr 26 17:17:12 gardeneast kernel: [160403.594707] [<c0555b30>] (dump_stack) from [<c0039d60>] (process_one_work+0x360/0x444)
Apr 26 17:17:12 gardeneast kernel: [160403.623210] [<c0039d60>] (process_one_work) from [<c003a998>] (worker_thread+0x190/0x580)
Apr 26 17:17:12 gardeneast kernel: [160403.651869] [<c003a998>] (worker_thread) from [<c003edf8>] (kthread+0xd8/0xf4)
Apr 26 17:17:12 gardeneast kernel: [160403.670260] [<c003edf8>] (kthread) from [<c000e988>] (ret_from_fork+0x14/0x20)
Apr 26 17:17:12 gardeneast kernel: [160403.688909] BUG: workqueue leaked lock or atomic: kworker/0:2/0xffffffff/4586
Apr 26 17:17:12 gardeneast kernel: [160403.688909]      last function: fb_flashcursor
Apr 26 17:17:12 gardeneast kernel: [160403.721667] CPU: 0 PID: 4586 Comm: kworker/0:2 Tainted: G      D W      3.18.7+ #755
Apr 26 17:17:12 gardeneast kernel: [160403.750935] Workqueue: events_power_efficient fb_flashcursor
Apr 26 17:17:12 gardeneast kernel: [160403.767903] [<c00151fc>] (unwind_backtrace) from [<c0012710>] (show_stack+0x20/0x24)
Apr 26 17:17:12 gardeneast kernel: [160403.796472] [<c0012710>] (show_stack) from [<c0555b30>] (dump_stack+0x20/0x28)
Apr 26 17:17:12 gardeneast kernel: [160403.815150] [<c0555b30>] (dump_stack) from [<c0039d60>] (process_one_work+0x360/0x444)
Apr 26 17:17:12 gardeneast kernel: [160403.843399] [<c0039d60>] (process_one_work) from [<c003a998>] (worker_thread+0x190/0x580)
Apr 26 17:17:12 gardeneast kernel: [160403.872901] [<c003a998>] (worker_thread) from [<c003edf8>] (kthread+0xd8/0xf4)
Apr 26 17:17:12 gardeneast kernel: [160403.891996] [<c003edf8>] (kthread) from [<c000e988>] (ret_from_fork+0x14/0x20)
Apr 26 17:17:12 gardeneast kernel: [160403.912141] BUG: workqueue leaked lock or atomic: kworker/0:2/0xffffffff/4586
Apr 26 17:17:12 gardeneast kernel: [160403.912141]      last function: BlinkWorkItemCallback [8192cu]
Apr 26 17:17:12 gardeneast kernel: [160403.946287] CPU: 0 PID: 4586 Comm: kworker/0:2 Tainted: G      D W      3.18.7+ #755
Apr 26 17:17:12 gardeneast kernel: [160403.975256] Workqueue: events BlinkWorkItemCallback [8192cu]
Apr 26 17:17:12 gardeneast kernel: [160403.991175] [<c00151fc>] (unwind_backtrace) from [<c0012710>] (show_stack+0x20/0x24)
Apr 26 17:17:12 gardeneast kernel: [160404.020100] [<c0012710>] (show_stack) from [<c0555b30>] (dump_stack+0x20/0x28)
Apr 26 17:17:12 gardeneast kernel: [160404.038625] [<c0555b30>] (dump_stack) from [<c0039d60>] (process_one_work+0x360/0x444)
Apr 26 17:17:12 gardeneast kernel: [160404.067273] [<c0039d60>] (process_one_work) from [<c003a998>] (worker_thread+0x190/0x580)
Apr 26 17:17:12 gardeneast kernel: [160404.095978] [<c003a998>] (worker_thread) from [<c003edf8>] (kthread+0xd8/0xf4)
Apr 26 17:17:12 gardeneast kernel: [160404.114522] [<c003edf8>] (kthread) from [<c000e988>] (ret_from_fork+0x14/0x20)
Apr 26 17:17:12 gardeneast kernel: [160404.133444] BUG: workqueue leaked lock or atomic: kworker/0:2/0xffffffff/4586
Apr 26 17:17:12 gardeneast kernel: [160404.133444]      last function: fb_flashcursor
Apr 26 17:17:12 gardeneast kernel: [160404.165922] CPU: 0 PID: 4586 Comm: kworker/0:2 Tainted: G      D W      3.18.7+ #755
Apr 26 17:17:12 gardeneast kernel: [160404.194346] Workqueue: events_power_efficient fb_flashcursor
Apr 26 17:17:12 gardeneast kernel: [160404.210311] [<c00151fc>] (unwind_backtrace) from [<c0012710>] (show_stack+0x20/0x24)
Apr 26 17:17:12 gardeneast kernel: [160404.239152] [<c0012710>] (show_stack) from [<c0555b30>] (dump_stack+0x20/0x28)
Apr 26 17:17:13 gardeneast kernel: [160404.257793] [<c0555b30>] (dump_stack) from [<c0039d60>] (process_one_work+0x360/0x444)
Apr 26 17:17:13 gardeneast kernel: [160404.289065] [<c0039d60>] (process_one_work) from [<c003a998>] (worker_thread+0x190/0x580)
Apr 26 17:17:13 gardeneast kernel: [160404.318293] [<c003a998>] (worker_thread) from [<c003edf8>] (kthread+0xd8/0xf4)
Apr 26 17:17:13 gardeneast kernel: [160404.337813] [<c003edf8>] (kthread) from [<c000e988>] (ret_from_fork+0x14/0x20)
Apr 26 17:17:13 gardeneast kernel: [160404.358465] BUG: workqueue leaked lock or atomic: kworker/0:2/0xffffffff/4586
Apr 26 17:17:13 gardeneast kernel: [160404.358465]      last function: od_dbs_timer
Apr 26 17:17:13 gardeneast kernel: [160404.392035] CPU: 0 PID: 4586 Comm: kworker/0:2 Tainted: G      D W      3.18.7+ #755
Apr 26 17:17:13 gardeneast kernel: [160404.420648] Workqueue: events od_dbs_timer
Apr 26 17:17:13 gardeneast kernel: [160404.436581] [<c00151fc>] (unwind_backtrace) from [<c0012710>] (show_stack+0x20/0x24)
Apr 26 17:17:13 gardeneast kernel: [160404.465130] [<c0012710>] (show_stack) from [<c0555b30>] (dump_stack+0x20/0x28)
Apr 26 17:17:13 gardeneast kernel: [160404.483737] [<c0555b30>] (dump_stack) from [<c0039d60>] (process_one_work+0x360/0x444)
Apr 26 17:17:13 gardeneast kernel: [160404.512941] [<c0039d60>] (process_one_work) from [<c003a998>] (worker_thread+0x190/0x580)
Apr 26 17:17:13 gardeneast kernel: [160404.542122] [<c003a998>] (worker_thread) from [<c003edf8>] (kthread+0xd8/0xf4)
Apr 26 17:17:13 gardeneast kernel: [160404.560879] [<c003edf8>] (kthread) from [<c000e988>] (ret_from_fork+0x14/0x20)
```

**This continues for a few minutes and afterwards it crashes:**

```
Apr 26 17:17:14 gardeneast kernel: [160405.761998] CPU: 0 PID: 4586 Comm: kworker/0:2 Tainted: G      D W      3.18.7+ #755
Apr 26 17:17:14 gardeneast kernel: [160405.793514] Workqueue: events od_dbs_timer
Apr 26 17:17:14 gardeneast kernel: [160405.808272] [<c00151fc>] (unwind_backtrace) from [<c0012710>] (show_stack+0x20/0x24)
Apr 26 17:17:14 gardeneast kernel: [160405.837937] [<c0012710>] (show_stack) from [<c0555b30>] (dump_stack+0x20/0x28)
Apr 26 17:17:14 gardeneast kernel: [160405.862826] [<c0555b30>] (dump_stack) from [<c0039d60>] (process_one_work+0x360/0x444)
Apr 26 17:17:14 gardeneast kernel: [160405.890940] [<c0039d60>] (process_one_work) from [<c003a998>] (worker_thread+0x190/0x580)
Apr 26 17:17:14 gardeneast kernel: [160405.919735] [<c003a998>] (worker_thread) from [<c003edf8>] (kthread+0xd8/0xf4)
Apr 26 17:17:14 gardeneast kernel: [160405.939493] [<c003edf8>] (kthread) from [<c000e988>] (ret_from_fork+0x14/0x20)
Apr 26 17:17:14 gardeneast kernel: [160405.958133] ------------[ cut here ]------------
Apr 26 17:17:14 gardeneast kernel: [160405.958151] kernel BUG at lib/genalloc.c:279!
Apr 26 17:17:14 gardeneast kernel: [160405.958159] Internal error: Oops - BUG: 0 [#2] PREEMPT ARM
Apr 26 17:17:14 gardeneast kernel: [160405.958201] Modules linked in: snd_bcm2835 snd_pcm snd_seq snd_seq_device snd_timer snd spi_bcm2708 8192cu uio_pdrv_genirq uio
Apr 26 17:17:14 gardeneast kernel: [160405.958219] CPU: 0 PID: 4586 Comm: kworker/0:2 Tainted: G      D W      3.18.7+ #755
Apr 26 17:17:14 gardeneast kernel: [160405.958262] Workqueue: events console_callback
Apr 26 17:17:14 gardeneast kernel: [160405.958272] task: d92fb600 ti: d9186000 task.ti: d9186000
Apr 26 17:17:14 gardeneast kernel: [160405.958298] PC is at gen_pool_alloc+0x23c/0x240
Apr 26 17:17:14 gardeneast kernel: [160405.958320] LR is at __dma_alloc+0x1cc/0x27c
Apr 26 17:17:14 gardeneast kernel: [160405.958332] pc : [<c03099cc>]    lr : [<c00199ac>]    psr: 00000013
Apr 26 17:17:14 gardeneast kernel: [160405.958332] sp : d9187c48  ip : d9187c98  fp : d9187c94
Apr 26 17:17:14 gardeneast kernel: [160405.958337] r10: 00000000  r9 : 00000000  r8 : d9187d2c
Apr 26 17:17:14 gardeneast kernel: [160405.958344] r7 : 00000247  r6 : 00000000  r5 : db113440  r4 : 00100000
Apr 26 17:17:14 gardeneast kernel: [160405.958351] r3 : 0000000c  r2 : d9187c48  r1 : 00001000  r0 : db113440
Apr 26 17:17:14 gardeneast kernel: [160405.958360] Flags: nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment kernel
Apr 26 17:17:14 gardeneast kernel: [160405.958369] Control: 00c5387d  Table: 1a318008  DAC: 00000015
Apr 26 17:17:14 gardeneast kernel: [160405.958376] Process kworker/0:2 (pid: 4586, stack limit = 0xd91861b0)
Apr 26 17:17:14 gardeneast kernel: [160405.958383] Stack: (0xd9187c48 to 0xd9188000)
Apr 26 17:17:14 gardeneast kernel: [160405.958399] 7c40:                   00000000 00000001 0000000c 00001000 00000000 de185400
Apr 26 17:17:14 gardeneast kernel: [160405.958415] 7c60: d9186038 db1f38a0 d9187d00 c0855ad0 00001000 00000000 00000247 d9187d2c
Apr 26 17:17:14 gardeneast kernel: [160405.958431] 7c80: 00000000 00000000 d9187cd4 d9187c98 c00199ac c030979c c0322120 c0329908
Apr 26 17:17:14 gardeneast kernel: [160405.958447] 7ca0: 00000010 c0019b7c d9187cec 00000000 d9187d2c 00001000 00000000 00000247
Apr 26 17:17:14 gardeneast kernel: [160405.958464] 7cc0: 00000020 c001dd08 d9187d14 d9187cd8 c0019bb8 c00197ec 00000247 00000000
Apr 26 17:17:14 gardeneast kernel: [160405.958480] 7ce0: c001dd08 c0321fac c0837108 00000000 00000000 0000001c 00001000 c080a3bc
Apr 26 17:17:14 gardeneast kernel: [160405.958498] 7d00: d9187d64 00000000 d9187d5c d9187d18 c001dd08 c0019b20 00000000 c03208d8
Apr 26 17:17:14 gardeneast kernel: [160405.958514] 7d20: ffffffff c0837aec ffffffff ffffffff 00000010 00000000 00000001 00000001
Apr 26 17:17:14 gardeneast kernel: [160405.958530] 7d40: db1f7600 00000000 00000000 00000000 d9187d94 d9187d60 c03298c4 c001dcb8
Apr 26 17:17:14 gardeneast kernel: [160405.958545] 7d60: d9187d84 0000001c 00000000 00040002 00000004 00000004 00000001 00000000
Apr 26 17:17:14 gardeneast kernel: [160405.958562] 7d80: db1c8400 00000000 d9187dbc d9187d98 c03229c4 c0329870 db003000 00000001
Apr 26 17:17:14 gardeneast kernel: [160405.958579] 7da0: db1c8400 d9187d9c db1c8400 db003000 d9187ea4 d9187dc0 c031e368 c032296c
Apr 26 17:17:14 gardeneast kernel: [160405.958594] 7dc0: 00000004 00000000 000000ff 00000002 00000000 d9180001 da251b20 00000000
Apr 26 17:17:14 gardeneast kernel: [160405.958608] 7de0: 00000000 00000190 00000008 00000010 00000007 00000000 00000001 c05a42f8
Apr 26 17:17:14 gardeneast kernel: [160405.958626] 7e00: c0761d38 c000e988 d9187fb0 d9187ea8 d9187ea4 c031d5c0 d9187e44 db003000
Apr 26 17:17:14 gardeneast kernel: [160405.958642] 7e20: db1c8400 00000002 00000720 db003104 db003118 c03216ac d9187e8c d9187e48
Apr 26 17:17:14 gardeneast kernel: [160405.958658] 7e40: c031e100 c03216b8 00000007 00000000 00000001 00000000 00000007 c08e192c
Apr 26 17:17:14 gardeneast kernel: [160405.958674] 7e60: 00000000 db003000 c08e1c5c c08e1c5c 00000000 db466c00 00000000 c08e1c5c
Apr 26 17:17:14 gardeneast kernel: [160405.958690] 7e80: db003000 c08e1c5c 00000000 db466c00 00000000 00000000 d9187ec4 d9187ea8
Apr 26 17:17:14 gardeneast kernel: [160405.958707] 7ea0: c0347dd0 c031e184 c08e1c5c c08e1c5c c080f1cc d9186030 d9187eec d9187ec8
Apr 26 17:17:14 gardeneast kernel: [160405.958723] 7ec0: c034ae2c c0347c18 c0012710 c0039b00 00000001 c0838e08 da307b40 c080f1cc
Apr 26 17:17:14 gardeneast kernel: [160405.958739] 7ee0: d9187f2c d9187ef0 c0039b3c c034adb4 c0420714 c080f1cc d9186030 c080f1cc
Apr 26 17:17:14 gardeneast kernel: [160405.958756] 7f00: da307b58 c080f1cc d9186030 c080f1dc da307b58 00000008 c080f1cc da307b40
Apr 26 17:17:14 gardeneast kernel: [160405.958772] 7f20: d9187f64 d9187f30 c003a998 c0039a0c 00000000 da307b40 c003a808 db3b2f60
Apr 26 17:17:14 gardeneast kernel: [160405.958788] 7f40: 00000000 da307b40 c003a808 00000000 00000000 00000000 d9187fac d9187f68
Apr 26 17:17:14 gardeneast kernel: [160405.958804] 7f60: c003edf8 c003a814 c0046010 00000000 60000013 da307b40 00000000 d9187f7c
Apr 26 17:17:14 gardeneast kernel: [160405.958821] 7f80: d9187f7c 00000000 d9187f88 d9187f88 db3b2f60 c003ed20 00000000 00000000
Apr 26 17:17:14 gardeneast kernel: [160405.958836] 7fa0: 00000000 d9187fb0 c000e988 c003ed2c 00000000 00000000 00000000 00000000
Apr 26 17:17:14 gardeneast kernel: [160405.958851] 7fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Apr 26 17:17:14 gardeneast kernel: [160405.958866] 7fe0: 00000000 00000000 00000000 00000000 00000013 00000000 1b7fa821 1b7fac21
Apr 26 17:17:14 gardeneast kernel: [160405.958901] [<c03099cc>] (gen_pool_alloc) from [<c00199ac>] (__dma_alloc+0x1cc/0x27c)
Apr 26 17:17:14 gardeneast kernel: [160405.958925] [<c00199ac>] (__dma_alloc) from [<c0019bb8>] (arm_dma_alloc+0xa4/0xb0)
Apr 26 17:17:14 gardeneast kernel: [160405.958947] [<c0019bb8>] (arm_dma_alloc) from [<c001dd08>] (bcm_mailbox_property+0x5c/0x1f0)
Apr 26 17:17:14 gardeneast kernel: [160405.958977] [<c001dd08>] (bcm_mailbox_property) from [<c03298c4>] (bcm2708_fb_blank+0x60/0x98)
Apr 26 17:17:14 gardeneast kernel: [160405.959001] [<c03298c4>] (bcm2708_fb_blank) from [<c03229c4>] (fb_blank+0x64/0xb8)
Apr 26 17:17:14 gardeneast kernel: [160405.959019] [<c03229c4>] (fb_blank) from [<c031e368>] (fbcon_blank+0x1f0/0x298)
Apr 26 17:17:14 gardeneast kernel: [160405.959042] [<c031e368>] (fbcon_blank) from [<c0347dd0>] (do_blank_screen+0x1c4/0x27c)
Apr 26 17:17:14 gardeneast kernel: [160405.959065] [<c0347dd0>] (do_blank_screen) from [<c034ae2c>] (console_callback+0x84/0x160)
Apr 26 17:17:14 gardeneast kernel: [160405.959091] [<c034ae2c>] (console_callback) from [<c0039b3c>] (process_one_work+0x13c/0x444)
Apr 26 17:17:14 gardeneast kernel: [160405.959111] [<c0039b3c>] (process_one_work) from [<c003a998>] (worker_thread+0x190/0x580)
Apr 26 17:17:14 gardeneast kernel: [160405.959137] [<c003a998>] (worker_thread) from [<c003edf8>] (kthread+0xd8/0xf4)
Apr 26 17:17:14 gardeneast kernel: [160405.959168] [<c003edf8>] (kthread) from [<c000e988>] (ret_from_fork+0x14/0x20)
Apr 26 17:17:14 gardeneast kernel: [160405.959183] Code: e1831f92 e3310000 1afffffa eaffffec (e7f001f2) 
Apr 26 17:17:14 gardeneast kernel: [160405.959198] ---[ end trace 48e359ef86e63f53 ]---
Apr 26 17:17:14 gardeneast kernel: [160405.959206] Kernel panic - not syncing: Fatal exception in interrupt
Apr 26 17:17:14 gardeneast kernel: [160405.959218] ---[ end Kernel panic - not syncing: Fatal exception in interrupt
Apr 26 17:19:38 gardeneast dhclient: DHCPREQUEST on wlan0 to 10.0.0.1 port 67
Apr 26 17:19:38 gardeneast dhclient: DHCPACK from 10.0.0.1
Apr 26 17:19:38 gardeneast dhclient: bound to 10.0.102.1 -- renewal in 3100 seconds.
Apr 26 17:17:19 gardeneast kernel: imklog 5.8.11, log source = /proc/kmsg started.
Apr 26 17:17:19 gardeneast rsyslogd: [origin software="rsyslogd" swVersion="5.8.11" x-pid="2052" x-info="http://www.rsyslog.com"] start
Apr 26 17:17:19 gardeneast kernel: [    0.000000] Booting Linux on physical CPU 0x0
Apr 26 17:17:19 gardeneast kernel: [    0.000000] Initializing cgroup subsys cpu
Apr 26 17:17:19 gardeneast kernel: [    0.000000] Initializing cgroup subsys cpuacct
```

**It's a rpi b+ with kernel 3.18.7 #755. I use the raspbian Image. There is a EDIMAX EW-7811UN that connects the rpi to the lan and Internet.**

**What causes this? Is it really a kernel bug? Can I do something about it?**

**Comment by Ruffio** [comment]
@marc40000 has your issue been resolved? If yes, then please close this issue.

**Comment by marc40000** [comment]
No. I still have issues with wifi rpis crashing every few days.

**Comment by popcornmix** [comment]
@marc40000 what does `vcgencmd version` and `uname -a` report?

**Comment by marc40000** [comment]
pi@gardeneast ~ $  vcgencmd version
Mar 15 2016 14:47:28
Copyright (c) 2012 Broadcom
version 1bf9a9a77026af9128a339c82d72e331d3532ee4 (clean) (release)

pi@gardeneast ~ $ uname -a
Linux gardeneast 4.1.19+ #858 Tue Mar 15 15:52:03 GMT 2016 armv6l GNU/Linux

I have several rpis running and they all work without issues. Only the 2 
that are connected by wifi regularly crash. I can't get them running in 
a stable way. I updated several times and sometimes it feels like it 
crashes less often and then a few weeks later after the next update it 
feels liek it gets worse again. Could be random though. I never had a 
version that didn't crash.

**Comment by marc40000** [comment]
Also, I don't know if it helps, but it feels like it always happens if there is a lot of wifi udp traffic going on.

**Comment by popcornmix** [comment]
The kernel for jessie is using 4.4 tree. 
You really should upgrade if you are having problems.
I'm not saying for certain it is fixed, but we can't do anything to help problems with an old kernel/firmware.

**Comment by marc40000** [comment]
Ok I'll upgrade

**Comment by marc40000** [comment]
Ok I upgraded. And I still have this issue. Random crashes. twice a weak on average.

**Comment by popcornmix** [comment]
What wireless devices are you using?
Are you able to connect ethernet to one of the Pi's just to confirm it is solved when wireless is not used?
An updated dmesg log would be useful (the line numbers in back trace don't match current kernel).

**Comment by JamesH65** [comment]
@marc40000 There have been some fixes for wireless and USB drivers in the latest kernel (4.9). Can you try those and see if the issue is fixed?

**Comment by JamesH65** [comment]
Closing due to lack of activity. Reopen if you feel this issue is still relevant.
